# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'form.ui'
#
# Created: Sun Jan 28 13:37:52 2018
#      by: PyQt5 UI code generator 5.2.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(840, 670)
        MainWindow.setMinimumSize(QtCore.QSize(840, 670))
        MainWindow.setMaximumSize(QtCore.QSize(840, 670))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("../Img/ico32_pgn_icon.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.mainTabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.mainTabWidget.setGeometry(QtCore.QRect(10, 10, 821, 561))
        self.mainTabWidget.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.mainTabWidget.setObjectName("mainTabWidget")
        self.tabMain = QtWidgets.QWidget()
        self.tabMain.setObjectName("tabMain")
        self.rfbTypeCombo = QtWidgets.QComboBox(self.tabMain)
        self.rfbTypeCombo.setGeometry(QtCore.QRect(80, 20, 111, 22))
        self.rfbTypeCombo.setObjectName("rfbTypeCombo")
        self.logGroupBox = QtWidgets.QGroupBox(self.tabMain)
        self.logGroupBox.setGeometry(QtCore.QRect(199, 280, 601, 201))
        self.logGroupBox.setObjectName("logGroupBox")
        self.listLog = QtWidgets.QListWidget(self.logGroupBox)
        self.listLog.setGeometry(QtCore.QRect(10, 30, 581, 171))
        self.listLog.setAutoFillBackground(False)
        self.listLog.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.listLog.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOn)
        self.listLog.setAutoScroll(True)
        self.listLog.setAutoScrollMargin(16)
        self.listLog.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.listLog.setTabKeyNavigation(False)
        self.listLog.setProperty("showDropIndicator", False)
        self.listLog.setDragDropMode(QtWidgets.QAbstractItemView.DragOnly)
        self.listLog.setAlternatingRowColors(False)
        self.listLog.setSelectionMode(QtWidgets.QAbstractItemView.NoSelection)
        self.listLog.setVerticalScrollMode(QtWidgets.QAbstractItemView.ScrollPerItem)
        self.listLog.setMovement(QtWidgets.QListView.Free)
        self.listLog.setFlow(QtWidgets.QListView.TopToBottom)
        self.listLog.setObjectName("listLog")
        self.clrLogBtn = QtWidgets.QPushButton(self.tabMain)
        self.clrLogBtn.setGeometry(QtCore.QRect(670, 490, 93, 28))
        self.clrLogBtn.setObjectName("clrLogBtn")
        self.label_9 = QtWidgets.QLabel(self.tabMain)
        self.label_9.setGeometry(QtCore.QRect(10, 20, 46, 13))
        self.label_9.setObjectName("label_9")
        self.startTestBtn = QtWidgets.QPushButton(self.tabMain)
        self.startTestBtn.setGeometry(QtCore.QRect(90, 500, 101, 31))
        self.startTestBtn.setObjectName("startTestBtn")
        self.testsGroupBox = QtWidgets.QGroupBox(self.tabMain)
        self.testsGroupBox.setGeometry(QtCore.QRect(0, 350, 191, 131))
        self.testsGroupBox.setObjectName("testsGroupBox")
        self.checkAlcTest = QtWidgets.QCheckBox(self.testsGroupBox)
        self.checkAlcTest.setGeometry(QtCore.QRect(10, 110, 70, 17))
        self.checkAlcTest.setChecked(True)
        self.checkAlcTest.setObjectName("checkAlcTest")
        self.checkGainTest = QtWidgets.QCheckBox(self.testsGroupBox)
        self.checkGainTest.setGeometry(QtCore.QRect(10, 30, 111, 17))
        self.checkGainTest.setChecked(True)
        self.checkGainTest.setAutoExclusive(False)
        self.checkGainTest.setObjectName("checkGainTest")
        self.checkDsaTest = QtWidgets.QCheckBox(self.testsGroupBox)
        self.checkDsaTest.setGeometry(QtCore.QRect(10, 50, 70, 17))
        self.checkDsaTest.setChecked(True)
        self.checkDsaTest.setAutoExclusive(False)
        self.checkDsaTest.setObjectName("checkDsaTest")
        self.checkBitAlarmTest = QtWidgets.QCheckBox(self.testsGroupBox)
        self.checkBitAlarmTest.setEnabled(True)
        self.checkBitAlarmTest.setGeometry(QtCore.QRect(10, 90, 70, 17))
        self.checkBitAlarmTest.setChecked(True)
        self.checkBitAlarmTest.setObjectName("checkBitAlarmTest")
        self.checkImTest = QtWidgets.QCheckBox(self.testsGroupBox)
        self.checkImTest.setGeometry(QtCore.QRect(10, 70, 101, 17))
        self.checkImTest.setChecked(True)
        self.checkImTest.setObjectName("checkImTest")
        self.label2 = QtWidgets.QLabel(self.tabMain)
        self.label2.setGeometry(QtCore.QRect(10, 50, 46, 13))
        self.label2.setObjectName("label2")
        self.rfbSN = QtWidgets.QLineEdit(self.tabMain)
        self.rfbSN.setGeometry(QtCore.QRect(80, 50, 113, 20))
        self.rfbSN.setText("")
        self.rfbSN.setMaxLength(10)
        self.rfbSN.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.rfbSN.setObjectName("rfbSN")
        self.tableSettings = QtWidgets.QTableWidget(self.tabMain)
        self.tableSettings.setGeometry(QtCore.QRect(10, 80, 181, 271))
        self.tableSettings.setMaximumSize(QtCore.QSize(181, 900))
        self.tableSettings.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.tableSettings.setAutoScroll(True)
        self.tableSettings.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.tableSettings.setRowCount(0)
        self.tableSettings.setColumnCount(2)
        self.tableSettings.setObjectName("tableSettings")
        item = QtWidgets.QTableWidgetItem()
        self.tableSettings.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableSettings.setHorizontalHeaderItem(1, item)
        self.tableSettings.verticalHeader().setVisible(False)
        self.tableSettings.verticalHeader().setHighlightSections(True)
        self.groupBox_7 = QtWidgets.QGroupBox(self.tabMain)
        self.groupBox_7.setGeometry(QtCore.QRect(200, 20, 601, 251))
        self.groupBox_7.setObjectName("groupBox_7")
        self.tableResult = QtWidgets.QTableWidget(self.groupBox_7)
        self.tableResult.setEnabled(True)
        self.tableResult.setGeometry(QtCore.QRect(10, 20, 581, 221))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tableResult.sizePolicy().hasHeightForWidth())
        self.tableResult.setSizePolicy(sizePolicy)
        self.tableResult.setMinimumSize(QtCore.QSize(0, 0))
        self.tableResult.setMaximumSize(QtCore.QSize(581, 16777215))
        self.tableResult.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.tableResult.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.tableResult.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.tableResult.setTabKeyNavigation(False)
        self.tableResult.setProperty("showDropIndicator", False)
        self.tableResult.setDragDropOverwriteMode(False)
        self.tableResult.setColumnCount(6)
        self.tableResult.setObjectName("tableResult")
        self.tableResult.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        item.setFont(font)
        self.tableResult.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableResult.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableResult.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableResult.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableResult.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.tableResult.setHorizontalHeaderItem(5, item)
        self.tableResult.horizontalHeader().setMinimumSectionSize(25)
        self.tableResult.verticalHeader().setVisible(False)
        self.tableResult.verticalHeader().setDefaultSectionSize(30)
        self.tableResult.verticalHeader().setHighlightSections(False)
        self.tableResult.verticalHeader().setMinimumSectionSize(17)
        self.groupBox_8 = QtWidgets.QGroupBox(self.tabMain)
        self.groupBox_8.setGeometry(QtCore.QRect(0, 490, 81, 41))
        self.groupBox_8.setObjectName("groupBox_8")
        self.testTimeLbl = QtWidgets.QLabel(self.groupBox_8)
        self.testTimeLbl.setGeometry(QtCore.QRect(10, 20, 61, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.testTimeLbl.setFont(font)
        self.testTimeLbl.setObjectName("testTimeLbl")
        self.layoutWidget = QtWidgets.QWidget(self.tabMain)
        self.layoutWidget.setGeometry(QtCore.QRect(230, 510, 81, 20))
        self.layoutWidget.setObjectName("layoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.layoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label4 = QtWidgets.QLabel(self.layoutWidget)
        self.label4.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label4.setObjectName("label4")
        self.horizontalLayout.addWidget(self.label4)
        self.dateCalibrLbl = QtWidgets.QLabel(self.layoutWidget)
        self.dateCalibrLbl.setObjectName("dateCalibrLbl")
        self.horizontalLayout.addWidget(self.dateCalibrLbl)
        self.layoutWidget1 = QtWidgets.QWidget(self.tabMain)
        self.layoutWidget1.setGeometry(QtCore.QRect(210, 490, 101, 16))
        self.layoutWidget1.setObjectName("layoutWidget1")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.layoutWidget1)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label3_2 = QtWidgets.QLabel(self.layoutWidget1)
        self.label3_2.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label3_2.setObjectName("label3_2")
        self.horizontalLayout_2.addWidget(self.label3_2)
        self.calibrLbl = QtWidgets.QLabel(self.layoutWidget1)
        self.calibrLbl.setObjectName("calibrLbl")
        self.horizontalLayout_2.addWidget(self.calibrLbl)
        self.layoutWidget2 = QtWidgets.QWidget(self.tabMain)
        self.layoutWidget2.setGeometry(QtCore.QRect(330, 490, 201, 42))
        self.layoutWidget2.setObjectName("layoutWidget2")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.layoutWidget2)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.currTestLbl = QtWidgets.QLabel(self.layoutWidget2)
        self.currTestLbl.setObjectName("currTestLbl")
        self.verticalLayout.addWidget(self.currTestLbl)
        self.TestPrBar = QtWidgets.QProgressBar(self.layoutWidget2)
        self.TestPrBar.setProperty("value", 24)
        self.TestPrBar.setObjectName("TestPrBar")
        self.verticalLayout.addWidget(self.TestPrBar)
        self.mainTabWidget.addTab(self.tabMain, "")
        self.tabJournal = QtWidgets.QWidget()
        self.tabJournal.setObjectName("tabJournal")
        self.tableJournal = QtWidgets.QTableWidget(self.tabJournal)
        self.tableJournal.setGeometry(QtCore.QRect(10, 40, 801, 411))
        self.tableJournal.viewport().setProperty("cursor", QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.tableJournal.setMouseTracking(True)
        self.tableJournal.setFocusPolicy(QtCore.Qt.WheelFocus)
        self.tableJournal.setToolTip("")
        self.tableJournal.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.tableJournal.setSelectionMode(QtWidgets.QAbstractItemView.SingleSelection)
        self.tableJournal.setObjectName("tableJournal")
        self.tableJournal.setColumnCount(13)
        self.tableJournal.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tableJournal.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableJournal.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableJournal.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableJournal.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableJournal.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableJournal.setHorizontalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableJournal.setHorizontalHeaderItem(6, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableJournal.setHorizontalHeaderItem(7, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableJournal.setHorizontalHeaderItem(8, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableJournal.setHorizontalHeaderItem(9, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableJournal.setHorizontalHeaderItem(10, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableJournal.setHorizontalHeaderItem(11, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableJournal.setHorizontalHeaderItem(12, item)
        self.tableJournal.horizontalHeader().setDefaultSectionSize(71)
        self.journalUpdateBtn = QtWidgets.QPushButton(self.tabJournal)
        self.journalUpdateBtn.setGeometry(QtCore.QRect(240, 10, 91, 21))
        self.journalUpdateBtn.setObjectName("journalUpdateBtn")
        self.journalDateStart = QtWidgets.QDateEdit(self.tabJournal)
        self.journalDateStart.setGeometry(QtCore.QRect(40, 10, 81, 22))
        self.journalDateStart.setLocale(QtCore.QLocale(QtCore.QLocale.Hebrew, QtCore.QLocale.Israel))
        self.journalDateStart.setObjectName("journalDateStart")
        self.journalDateStop = QtWidgets.QDateEdit(self.tabJournal)
        self.journalDateStop.setGeometry(QtCore.QRect(150, 11, 81, 21))
        self.journalDateStop.setLocale(QtCore.QLocale(QtCore.QLocale.Hebrew, QtCore.QLocale.Israel))
        self.journalDateStop.setObjectName("journalDateStop")
        self.printReportBtn = QtWidgets.QPushButton(self.tabJournal)
        self.printReportBtn.setGeometry(QtCore.QRect(230, 470, 91, 21))
        self.printReportBtn.setObjectName("printReportBtn")
        self.journalFilter = QtWidgets.QLineEdit(self.tabJournal)
        self.journalFilter.setGeometry(QtCore.QRect(370, 10, 91, 20))
        self.journalFilter.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.journalFilter.setText("")
        self.journalFilter.setMaxLength(16)
        self.journalFilter.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.journalFilter.setObjectName("journalFilter")
        self.label5 = QtWidgets.QLabel(self.tabJournal)
        self.label5.setGeometry(QtCore.QRect(340, 10, 31, 21))
        self.label5.setObjectName("label5")
        self.label6 = QtWidgets.QLabel(self.tabJournal)
        self.label6.setGeometry(QtCore.QRect(10, 10, 31, 21))
        self.label6.setObjectName("label6")
        self.label7 = QtWidgets.QLabel(self.tabJournal)
        self.label7.setGeometry(QtCore.QRect(130, 10, 16, 21))
        self.label7.setObjectName("label7")
        self.logoAxellRadio = QtWidgets.QRadioButton(self.tabJournal)
        self.logoAxellRadio.setGeometry(QtCore.QRect(10, 490, 51, 17))
        self.logoAxellRadio.setChecked(False)
        self.logoAxellRadio.setObjectName("logoAxellRadio")
        self.logoCobhamRadio = QtWidgets.QRadioButton(self.tabJournal)
        self.logoCobhamRadio.setGeometry(QtCore.QRect(10, 470, 61, 17))
        self.logoCobhamRadio.setChecked(True)
        self.logoCobhamRadio.setObjectName("logoCobhamRadio")
        self.reportTemplateCombo = QtWidgets.QComboBox(self.tabJournal)
        self.reportTemplateCombo.setGeometry(QtCore.QRect(80, 470, 131, 22))
        self.reportTemplateCombo.setObjectName("reportTemplateCombo")
        self.label8 = QtWidgets.QLabel(self.tabJournal)
        self.label8.setGeometry(QtCore.QRect(80, 450, 81, 16))
        self.label8.setObjectName("label8")
        self.label9 = QtWidgets.QLabel(self.tabJournal)
        self.label9.setGeometry(QtCore.QRect(10, 450, 81, 16))
        self.label9.setObjectName("label9")
        self.mainTabWidget.addTab(self.tabJournal, "")
        self.tabSettings = QtWidgets.QWidget()
        self.tabSettings.setObjectName("tabSettings")
        self.groupBox_9 = QtWidgets.QGroupBox(self.tabSettings)
        self.groupBox_9.setGeometry(QtCore.QRect(10, 10, 541, 151))
        self.groupBox_9.setObjectName("groupBox_9")
        self.instrAddrCombo = QtWidgets.QComboBox(self.groupBox_9)
        self.instrAddrCombo.setGeometry(QtCore.QRect(10, 90, 181, 22))
        self.instrAddrCombo.setObjectName("instrAddrCombo")
        self.currSaLbl = QtWidgets.QLabel(self.groupBox_9)
        self.currSaLbl.setGeometry(QtCore.QRect(60, 20, 211, 16))
        self.currSaLbl.setObjectName("currSaLbl")
        self.currGenLbl = QtWidgets.QLabel(self.groupBox_9)
        self.currGenLbl.setGeometry(QtCore.QRect(60, 40, 211, 16))
        self.currGenLbl.setObjectName("currGenLbl")
        self.setSaRadio = QtWidgets.QRadioButton(self.groupBox_9)
        self.setSaRadio.setGeometry(QtCore.QRect(10, 20, 41, 17))
        self.setSaRadio.setChecked(True)
        self.setSaRadio.setObjectName("setSaRadio")
        self.setGenRadio = QtWidgets.QRadioButton(self.groupBox_9)
        self.setGenRadio.setGeometry(QtCore.QRect(10, 40, 51, 17))
        self.setGenRadio.setObjectName("setGenRadio")
        self.label0 = QtWidgets.QLabel(self.groupBox_9)
        self.label0.setGeometry(QtCore.QRect(210, 90, 51, 20))
        self.label0.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label0.setObjectName("label0")
        self.label1 = QtWidgets.QLabel(self.groupBox_9)
        self.label1.setGeometry(QtCore.QRect(310, 90, 61, 20))
        self.label1.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label1.setObjectName("label1")
        self.saAtten = QtWidgets.QLineEdit(self.groupBox_9)
        self.saAtten.setGeometry(QtCore.QRect(270, 90, 31, 20))
        self.saAtten.setAlignment(QtCore.Qt.AlignCenter)
        self.saAtten.setObjectName("saAtten")
        self.genAtten = QtWidgets.QLineEdit(self.groupBox_9)
        self.genAtten.setGeometry(QtCore.QRect(380, 90, 31, 20))
        self.genAtten.setAlignment(QtCore.Qt.AlignCenter)
        self.genAtten.setObjectName("genAtten")
        self.saAtten1 = QtWidgets.QLineEdit(self.groupBox_9)
        self.saAtten1.setGeometry(QtCore.QRect(20, 190, 31, 20))
        self.saAtten1.setAlignment(QtCore.Qt.AlignCenter)
        self.saAtten1.setObjectName("saAtten1")
        self.setNaRadio = QtWidgets.QRadioButton(self.groupBox_9)
        self.setNaRadio.setGeometry(QtCore.QRect(10, 60, 51, 17))
        self.setNaRadio.setObjectName("setNaRadio")
        self.currNaLbl = QtWidgets.QLabel(self.groupBox_9)
        self.currNaLbl.setGeometry(QtCore.QRect(60, 59, 211, 16))
        self.currNaLbl.setObjectName("currNaLbl")
        self.setInstrBtn = QtWidgets.QPushButton(self.groupBox_9)
        self.setInstrBtn.setGeometry(QtCore.QRect(10, 120, 91, 23))
        self.setInstrBtn.setObjectName("setInstrBtn")
        self.currSaNameLbl = QtWidgets.QLabel(self.groupBox_9)
        self.currSaNameLbl.setGeometry(QtCore.QRect(280, 20, 241, 21))
        self.currSaNameLbl.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.currSaNameLbl.setObjectName("currSaNameLbl")
        self.currGenNameLbl = QtWidgets.QLabel(self.groupBox_9)
        self.currGenNameLbl.setGeometry(QtCore.QRect(280, 40, 241, 20))
        self.currGenNameLbl.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.currGenNameLbl.setObjectName("currGenNameLbl")
        self.currNaNameLbl = QtWidgets.QLabel(self.groupBox_9)
        self.currNaNameLbl.setGeometry(QtCore.QRect(280, 60, 231, 20))
        self.currNaNameLbl.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.currNaNameLbl.setObjectName("currNaNameLbl")
        self.label21 = QtWidgets.QLabel(self.groupBox_9)
        self.label21.setGeometry(QtCore.QRect(420, 90, 61, 20))
        self.label21.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label21.setObjectName("label21")
        self.naAtten = QtWidgets.QLineEdit(self.groupBox_9)
        self.naAtten.setGeometry(QtCore.QRect(490, 90, 31, 20))
        self.naAtten.setAlignment(QtCore.Qt.AlignCenter)
        self.naAtten.setObjectName("naAtten")
        self.line = QtWidgets.QFrame(self.groupBox_9)
        self.line.setGeometry(QtCore.QRect(60, 30, 461, 16))
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.line1 = QtWidgets.QFrame(self.groupBox_9)
        self.line1.setGeometry(QtCore.QRect(60, 50, 461, 16))
        self.line1.setFrameShape(QtWidgets.QFrame.HLine)
        self.line1.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line1.setObjectName("line1")
        self.groupBox_10 = QtWidgets.QGroupBox(self.tabSettings)
        self.groupBox_10.setGeometry(QtCore.QRect(10, 160, 221, 151))
        self.groupBox_10.setObjectName("groupBox_10")
        self.layoutWidget3 = QtWidgets.QWidget(self.groupBox_10)
        self.layoutWidget3.setGeometry(QtCore.QRect(1, 20, 123, 19))
        self.layoutWidget3.setObjectName("layoutWidget3")
        self.gridLayout = QtWidgets.QGridLayout(self.layoutWidget3)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.label3 = QtWidgets.QLabel(self.layoutWidget3)
        self.label3.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label3.setObjectName("label3")
        self.gridLayout.addWidget(self.label3, 0, 0, 1, 1)
        self.testSetDsaFull = QtWidgets.QRadioButton(self.layoutWidget3)
        self.testSetDsaFull.setObjectName("testSetDsaFull")
        self.gridLayout.addWidget(self.testSetDsaFull, 0, 1, 1, 1)
        self.testSetDsaShort = QtWidgets.QRadioButton(self.layoutWidget3)
        self.testSetDsaShort.setChecked(True)
        self.testSetDsaShort.setObjectName("testSetDsaShort")
        self.gridLayout.addWidget(self.testSetDsaShort, 0, 2, 1, 1)
        self.useThread = QtWidgets.QCheckBox(self.groupBox_10)
        self.useThread.setGeometry(QtCore.QRect(130, 20, 81, 17))
        self.useThread.setObjectName("useThread")
        self.groupBox_11 = QtWidgets.QGroupBox(self.tabSettings)
        self.groupBox_11.setGeometry(QtCore.QRect(10, 320, 201, 151))
        self.groupBox_11.setObjectName("groupBox_11")
        self.calibrationBtn = QtWidgets.QPushButton(self.groupBox_11)
        self.calibrationBtn.setGeometry(QtCore.QRect(10, 100, 81, 31))
        self.calibrationBtn.setObjectName("calibrationBtn")
        self.clearCalBtn = QtWidgets.QPushButton(self.groupBox_11)
        self.clearCalBtn.setGeometry(QtCore.QRect(100, 100, 81, 31))
        self.clearCalBtn.setObjectName("clearCalBtn")
        self.calAllBands = QtWidgets.QCheckBox(self.groupBox_11)
        self.calAllBands.setGeometry(QtCore.QRect(10, 20, 111, 17))
        self.calAllBands.setObjectName("calAllBands")
        self.calibrStart = QtWidgets.QLineEdit(self.groupBox_11)
        self.calibrStart.setGeometry(QtCore.QRect(50, 40, 31, 20))
        self.calibrStart.setMaxLength(4)
        self.calibrStart.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.calibrStart.setObjectName("calibrStart")
        self.calibrStop = QtWidgets.QLineEdit(self.groupBox_11)
        self.calibrStop.setGeometry(QtCore.QRect(50, 70, 31, 20))
        self.calibrStop.setMaxLength(4)
        self.calibrStop.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.calibrStop.setObjectName("calibrStop")
        self.label41 = QtWidgets.QLabel(self.groupBox_11)
        self.label41.setGeometry(QtCore.QRect(10, 40, 31, 20))
        self.label41.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label41.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label41.setObjectName("label41")
        self.label51 = QtWidgets.QLabel(self.groupBox_11)
        self.label51.setGeometry(QtCore.QRect(10, 70, 31, 20))
        self.label51.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label51.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label51.setObjectName("label51")
        self.label61 = QtWidgets.QLabel(self.groupBox_11)
        self.label61.setGeometry(QtCore.QRect(90, 40, 21, 20))
        self.label61.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label61.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label61.setObjectName("label61")
        self.label71 = QtWidgets.QLabel(self.groupBox_11)
        self.label71.setGeometry(QtCore.QRect(90, 70, 21, 20))
        self.label71.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label71.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label71.setObjectName("label71")
        self.groupBox_12 = QtWidgets.QGroupBox(self.tabSettings)
        self.groupBox_12.setGeometry(QtCore.QRect(240, 160, 311, 51))
        self.groupBox_12.setObjectName("groupBox_12")
        self.newRfbBtn = QtWidgets.QPushButton(self.groupBox_12)
        self.newRfbBtn.setGeometry(QtCore.QRect(220, 20, 81, 23))
        self.newRfbBtn.setObjectName("newRfbBtn")
        self.label81 = QtWidgets.QLabel(self.groupBox_12)
        self.label81.setGeometry(QtCore.QRect(40, 20, 46, 13))
        self.label81.setObjectName("label81")
        self.editRfbCombo = QtWidgets.QComboBox(self.groupBox_12)
        self.editRfbCombo.setGeometry(QtCore.QRect(100, 20, 111, 22))
        self.editRfbCombo.setObjectName("editRfbCombo")
        self.applySetBtn = QtWidgets.QPushButton(self.tabSettings)
        self.applySetBtn.setEnabled(True)
        self.applySetBtn.setGeometry(QtCore.QRect(10, 480, 75, 23))
        self.applySetBtn.setObjectName("applySetBtn")
        self.mainTabWidget.addTab(self.tabSettings, "")
        self.groupBox = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox.setGeometry(QtCore.QRect(10, 570, 81, 61))
        self.groupBox.setObjectName("groupBox")
        self.splitter = QtWidgets.QSplitter(self.groupBox)
        self.splitter.setGeometry(QtCore.QRect(10, 20, 61, 16))
        self.splitter.setOrientation(QtCore.Qt.Horizontal)
        self.splitter.setObjectName("splitter")
        self.label = QtWidgets.QLabel(self.splitter)
        self.label.setObjectName("label")
        self.portLbl = QtWidgets.QLabel(self.splitter)
        self.portLbl.setEnabled(True)
        self.portLbl.setObjectName("portLbl")
        self.splitter_2 = QtWidgets.QSplitter(self.groupBox)
        self.splitter_2.setGeometry(QtCore.QRect(10, 40, 61, 16))
        self.splitter_2.setOrientation(QtCore.Qt.Horizontal)
        self.splitter_2.setObjectName("splitter_2")
        self.label1 = QtWidgets.QLabel(self.splitter_2)
        self.label1.setObjectName("label1")
        self.baudLbl = QtWidgets.QLabel(self.splitter_2)
        self.baudLbl.setObjectName("baudLbl")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 840, 20))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtWidgets.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        self.menuEdit = QtWidgets.QMenu(self.menubar)
        self.menuEdit.setObjectName("menuEdit")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.action1 = QtWidgets.QAction(MainWindow)
        self.action1.setObjectName("action1")
        self.action2 = QtWidgets.QAction(MainWindow)
        self.action2.setObjectName("action2")
        self.menuFile.addAction(self.action1)
        self.menuFile.addAction(self.action2)
        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuEdit.menuAction())

        self.retranslateUi(MainWindow)
        self.mainTabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "RFBCheck v0.1.22 20180122"))
        self.logGroupBox.setTitle(_translate("MainWindow", "Log"))
        self.clrLogBtn.setText(_translate("MainWindow", "Clear Log"))
        self.label_9.setText(_translate("MainWindow", "RFB type:"))
        self.startTestBtn.setText(_translate("MainWindow", "Start"))
        self.testsGroupBox.setTitle(_translate("MainWindow", "Tests"))
        self.checkAlcTest.setText(_translate("MainWindow", "ALC"))
        self.checkGainTest.setText(_translate("MainWindow", "Gain and flatness"))
        self.checkDsaTest.setText(_translate("MainWindow", "DSA"))
        self.checkBitAlarmTest.setText(_translate("MainWindow", "BIT alarm"))
        self.checkImTest.setText(_translate("MainWindow", "Intermodulation"))
        self.label2.setText(_translate("MainWindow", "RFB SN:"))
        item = self.tableSettings.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Settings"))
        item = self.tableSettings.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Value"))
        self.groupBox_7.setTitle(_translate("MainWindow", "Result"))
        item = self.tableResult.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Test name"))
        item = self.tableResult.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Dl/Ul"))
        item = self.tableResult.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "Min"))
        item = self.tableResult.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "Current"))
        item = self.tableResult.horizontalHeaderItem(4)
        item.setText(_translate("MainWindow", "Max"))
        item = self.tableResult.horizontalHeaderItem(5)
        item.setText(_translate("MainWindow", "Result"))
        self.groupBox_8.setTitle(_translate("MainWindow", "Test timer"))
        self.testTimeLbl.setText(_translate("MainWindow", "0:00:00"))
        self.label4.setText(_translate("MainWindow", "Date:"))
        self.dateCalibrLbl.setText(_translate("MainWindow", "none"))
        self.label3_2.setText(_translate("MainWindow", "Calibration:"))
        self.calibrLbl.setText(_translate("MainWindow", "none"))
        self.currTestLbl.setText(_translate("MainWindow", "none"))
        self.mainTabWidget.setTabText(self.mainTabWidget.indexOf(self.tabMain), _translate("MainWindow", "Main"))
        self.tableJournal.setSortingEnabled(False)
        item = self.tableJournal.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "RFB type"))
        item = self.tableJournal.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "DSA 1"))
        item = self.tableJournal.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "Date test"))
        item = self.tableJournal.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "Band"))
        item = self.tableJournal.horizontalHeaderItem(4)
        item.setText(_translate("MainWindow", "Gain"))
        item = self.tableJournal.horizontalHeaderItem(5)
        item.setText(_translate("MainWindow", "Flatness"))
        item = self.tableJournal.horizontalHeaderItem(6)
        item.setText(_translate("MainWindow", "New Column"))
        item = self.tableJournal.horizontalHeaderItem(7)
        item.setText(_translate("MainWindow", "DSA 2"))
        item = self.tableJournal.horizontalHeaderItem(8)
        item.setText(_translate("MainWindow", "DSA 3"))
        item = self.tableJournal.horizontalHeaderItem(9)
        item.setText(_translate("MainWindow", "IMod"))
        item = self.tableJournal.horizontalHeaderItem(10)
        item.setText(_translate("MainWindow", "BIT"))
        item = self.tableJournal.horizontalHeaderItem(11)
        item.setText(_translate("MainWindow", "ALC In"))
        item = self.tableJournal.horizontalHeaderItem(12)
        item.setText(_translate("MainWindow", "ALC Out"))
        self.journalUpdateBtn.setText(_translate("MainWindow", "Update"))
        self.journalDateStart.setDisplayFormat(_translate("MainWindow", "dd.MM.yyyy"))
        self.journalDateStop.setDisplayFormat(_translate("MainWindow", "dd.MM.yyyy"))
        self.printReportBtn.setText(_translate("MainWindow", "Print report"))
        self.label5.setText(_translate("MainWindow", "Filter:"))
        self.label6.setText(_translate("MainWindow", "From:"))
        self.label7.setText(_translate("MainWindow", "To:"))
        self.logoAxellRadio.setText(_translate("MainWindow", "Axell"))
        self.logoCobhamRadio.setText(_translate("MainWindow", "Cobham"))
        self.label8.setText(_translate("MainWindow", "Report template:"))
        self.label9.setText(_translate("MainWindow", "Logo:"))
        self.mainTabWidget.setTabText(self.mainTabWidget.indexOf(self.tabJournal), _translate("MainWindow", "Journal"))
        self.groupBox_9.setTitle(_translate("MainWindow", "Instruments"))
        self.currSaLbl.setText(_translate("MainWindow", "TextLabel"))
        self.currGenLbl.setText(_translate("MainWindow", "TextLabel"))
        self.setSaRadio.setText(_translate("MainWindow", "SA:"))
        self.setGenRadio.setText(_translate("MainWindow", "GEN:"))
        self.label0.setText(_translate("MainWindow", "SA atten.:"))
        self.label1.setText(_translate("MainWindow", "GEN atten.:"))
        self.setNaRadio.setText(_translate("MainWindow", "NA:"))
        self.currNaLbl.setText(_translate("MainWindow", "TextLabel"))
        self.setInstrBtn.setText(_translate("MainWindow", "Set"))
        self.currSaNameLbl.setText(_translate("MainWindow", "TextLabel"))
        self.currGenNameLbl.setText(_translate("MainWindow", "TextLabel"))
        self.currNaNameLbl.setText(_translate("MainWindow", "TextLabel"))
        self.label21.setText(_translate("MainWindow", "NA atten.:"))
        self.groupBox_10.setTitle(_translate("MainWindow", "Test settings"))
        self.label3.setText(_translate("MainWindow", "DSA:"))
        self.testSetDsaFull.setText(_translate("MainWindow", "full"))
        self.testSetDsaShort.setText(_translate("MainWindow", "short"))
        self.useThread.setText(_translate("MainWindow", "Use thread"))
        self.groupBox_11.setTitle(_translate("MainWindow", "Calibration"))
        self.calibrationBtn.setText(_translate("MainWindow", "Calibration"))
        self.clearCalBtn.setText(_translate("MainWindow", "Clear cal.table"))
        self.calAllBands.setText(_translate("MainWindow", "Calibtate all bands"))
        self.label41.setText(_translate("MainWindow", "Start:"))
        self.label51.setText(_translate("MainWindow", "Stop:"))
        self.label61.setText(_translate("MainWindow", "MHz"))
        self.label71.setText(_translate("MainWindow", "MHz"))
        self.groupBox_12.setTitle(_translate("MainWindow", "RFB ATR settings"))
        self.newRfbBtn.setText(_translate("MainWindow", "New/Edit"))
        self.label81.setText(_translate("MainWindow", "RFB type:"))
        self.applySetBtn.setText(_translate("MainWindow", "Apply SetFile"))
        self.mainTabWidget.setTabText(self.mainTabWidget.indexOf(self.tabSettings), _translate("MainWindow", "Settings"))
        self.groupBox.setTitle(_translate("MainWindow", "Connection"))
        self.label.setText(_translate("MainWindow", "Port :"))
        self.portLbl.setText(_translate("MainWindow", "port"))
        self.label1.setText(_translate("MainWindow", "Baud:"))
        self.baudLbl.setText(_translate("MainWindow", "baud"))
        self.menuFile.setTitle(_translate("MainWindow", "File"))
        self.menuEdit.setTitle(_translate("MainWindow", "Edit"))
        self.action1.setText(_translate("MainWindow", "1"))
        self.action2.setText(_translate("MainWindow", "2"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())

