# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainwindow.ui'
#
# Created by: PyQt5 UI code generator 5.5.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.setWindowModality(QtCore.Qt.ApplicationModal)
        MainWindow.resize(910, 720)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        MainWindow.setMinimumSize(QtCore.QSize(910, 720))
        MainWindow.setMaximumSize(QtCore.QSize(16777215, 16777215))
        MainWindow.setWindowTitle("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("../../../Documents and Settings/Axell/.designer/Img/ico32_pgn_icon.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        MainWindow.setToolButtonStyle(QtCore.Qt.ToolButtonIconOnly)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout_8 = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout_8.setObjectName("gridLayout_8")
        self.mainTabWidget = QtWidgets.QTabWidget(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(100)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.mainTabWidget.sizePolicy().hasHeightForWidth())
        self.mainTabWidget.setSizePolicy(sizePolicy)
        self.mainTabWidget.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.mainTabWidget.setDocumentMode(False)
        self.mainTabWidget.setTabsClosable(False)
        self.mainTabWidget.setMovable(False)
        self.mainTabWidget.setTabBarAutoHide(False)
        self.mainTabWidget.setObjectName("mainTabWidget")
        self.tabMain = QtWidgets.QWidget()
        self.tabMain.setObjectName("tabMain")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.tabMain)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.logGroupBox = QtWidgets.QGroupBox(self.tabMain)
        self.logGroupBox.setMinimumSize(QtCore.QSize(581, 184))
        self.logGroupBox.setMaximumSize(QtCore.QSize(16777215, 201))
        self.logGroupBox.setObjectName("logGroupBox")
        self.gridLayout_11 = QtWidgets.QGridLayout(self.logGroupBox)
        self.gridLayout_11.setObjectName("gridLayout_11")
        self.listLog = QtWidgets.QListWidget(self.logGroupBox)
        self.listLog.setMinimumSize(QtCore.QSize(559, 150))
        self.listLog.setMaximumSize(QtCore.QSize(16777215, 150))
        self.listLog.setAutoFillBackground(False)
        self.listLog.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.listLog.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOn)
        self.listLog.setAutoScroll(True)
        self.listLog.setAutoScrollMargin(16)
        self.listLog.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.listLog.setTabKeyNavigation(False)
        self.listLog.setProperty("showDropIndicator", False)
        self.listLog.setDragDropMode(QtWidgets.QAbstractItemView.DragOnly)
        self.listLog.setAlternatingRowColors(False)
        self.listLog.setSelectionMode(QtWidgets.QAbstractItemView.NoSelection)
        self.listLog.setVerticalScrollMode(QtWidgets.QAbstractItemView.ScrollPerItem)
        self.listLog.setMovement(QtWidgets.QListView.Free)
        self.listLog.setFlow(QtWidgets.QListView.TopToBottom)
        self.listLog.setObjectName("listLog")
        self.gridLayout_11.addWidget(self.listLog, 0, 0, 1, 1)
        self.gridLayout_4.addWidget(self.logGroupBox, 2, 1, 1, 1)
        self.gridLayout_6 = QtWidgets.QGridLayout()
        self.gridLayout_6.setSizeConstraint(QtWidgets.QLayout.SetMaximumSize)
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.groupBox_3 = QtWidgets.QGroupBox(self.tabMain)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox_3.sizePolicy().hasHeightForWidth())
        self.groupBox_3.setSizePolicy(sizePolicy)
        self.groupBox_3.setMinimumSize(QtCore.QSize(211, 332))
        self.groupBox_3.setMaximumSize(QtCore.QSize(211, 16777215))
        self.groupBox_3.setObjectName("groupBox_3")
        self.gridLayout_9 = QtWidgets.QGridLayout(self.groupBox_3)
        self.gridLayout_9.setObjectName("gridLayout_9")
        self.tableSettings = QtWidgets.QTableWidget(self.groupBox_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tableSettings.sizePolicy().hasHeightForWidth())
        self.tableSettings.setSizePolicy(sizePolicy)
        self.tableSettings.setMinimumSize(QtCore.QSize(191, 299))
        self.tableSettings.setMaximumSize(QtCore.QSize(191, 16777215))
        self.tableSettings.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.tableSettings.setAutoScroll(True)
        self.tableSettings.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.tableSettings.setRowCount(0)
        self.tableSettings.setColumnCount(2)
        self.tableSettings.setObjectName("tableSettings")
        item = QtWidgets.QTableWidgetItem()
        self.tableSettings.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableSettings.setHorizontalHeaderItem(1, item)
        self.tableSettings.verticalHeader().setVisible(False)
        self.tableSettings.verticalHeader().setHighlightSections(True)
        self.gridLayout_9.addWidget(self.tableSettings, 0, 0, 1, 1)
        self.gridLayout_6.addWidget(self.groupBox_3, 0, 0, 1, 1)
        self.groupBox_7 = QtWidgets.QGroupBox(self.tabMain)
        self.groupBox_7.setObjectName("groupBox_7")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.groupBox_7)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.tableResult = QtWidgets.QTableWidget(self.groupBox_7)
        self.tableResult.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tableResult.sizePolicy().hasHeightForWidth())
        self.tableResult.setSizePolicy(sizePolicy)
        self.tableResult.setMinimumSize(QtCore.QSize(559, 299))
        self.tableResult.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.tableResult.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.tableResult.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.tableResult.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.tableResult.setTabKeyNavigation(False)
        self.tableResult.setProperty("showDropIndicator", False)
        self.tableResult.setDragDropOverwriteMode(False)
        self.tableResult.setColumnCount(6)
        self.tableResult.setObjectName("tableResult")
        self.tableResult.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        item.setFont(font)
        self.tableResult.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableResult.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableResult.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableResult.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableResult.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignVCenter)
        self.tableResult.setHorizontalHeaderItem(5, item)
        self.tableResult.horizontalHeader().setMinimumSectionSize(25)
        self.tableResult.verticalHeader().setVisible(False)
        self.tableResult.verticalHeader().setDefaultSectionSize(30)
        self.tableResult.verticalHeader().setHighlightSections(False)
        self.tableResult.verticalHeader().setMinimumSectionSize(17)
        self.gridLayout_5.addWidget(self.tableResult, 0, 0, 1, 1)
        self.gridLayout_6.addWidget(self.groupBox_7, 0, 1, 1, 1)
        self.gridLayout_4.addLayout(self.gridLayout_6, 1, 0, 1, 2)
        self.horizontalLayout_12 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_12.setObjectName("horizontalLayout_12")
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.label_9 = QtWidgets.QLabel(self.tabMain)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_9.sizePolicy().hasHeightForWidth())
        self.label_9.setSizePolicy(sizePolicy)
        self.label_9.setMaximumSize(QtCore.QSize(46, 13))
        self.label_9.setObjectName("label_9")
        self.horizontalLayout_8.addWidget(self.label_9)
        self.rfbTypeCombo = QtWidgets.QComboBox(self.tabMain)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.rfbTypeCombo.sizePolicy().hasHeightForWidth())
        self.rfbTypeCombo.setSizePolicy(sizePolicy)
        self.rfbTypeCombo.setMinimumSize(QtCore.QSize(120, 20))
        self.rfbTypeCombo.setMaximumSize(QtCore.QSize(120, 20))
        self.rfbTypeCombo.setObjectName("rfbTypeCombo")
        self.horizontalLayout_8.addWidget(self.rfbTypeCombo)
        self.horizontalLayout_12.addLayout(self.horizontalLayout_8)
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.label2 = QtWidgets.QLabel(self.tabMain)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label2.sizePolicy().hasHeightForWidth())
        self.label2.setSizePolicy(sizePolicy)
        self.label2.setMaximumSize(QtCore.QSize(46, 13))
        self.label2.setObjectName("label2")
        self.horizontalLayout_9.addWidget(self.label2)
        self.rfbSN = QtWidgets.QLineEdit(self.tabMain)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.rfbSN.sizePolicy().hasHeightForWidth())
        self.rfbSN.setSizePolicy(sizePolicy)
        self.rfbSN.setMinimumSize(QtCore.QSize(120, 20))
        self.rfbSN.setMaximumSize(QtCore.QSize(120, 20))
        self.rfbSN.setText("")
        self.rfbSN.setMaxLength(32)
        self.rfbSN.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.rfbSN.setObjectName("rfbSN")
        self.horizontalLayout_9.addWidget(self.rfbSN)
        self.horizontalLayout_12.addLayout(self.horizontalLayout_9)
        self.horizontalLayout_13 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_13.setObjectName("horizontalLayout_13")
        self.label3_2 = QtWidgets.QLabel(self.tabMain)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label3_2.setFont(font)
        self.label3_2.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label3_2.setObjectName("label3_2")
        self.horizontalLayout_13.addWidget(self.label3_2)
        self.calibrLbl = QtWidgets.QLabel(self.tabMain)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.calibrLbl.setFont(font)
        self.calibrLbl.setObjectName("calibrLbl")
        self.horizontalLayout_13.addWidget(self.calibrLbl)
        self.horizontalLayout_12.addLayout(self.horizontalLayout_13)
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.label4 = QtWidgets.QLabel(self.tabMain)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label4.setFont(font)
        self.label4.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label4.setObjectName("label4")
        self.horizontalLayout_6.addWidget(self.label4)
        self.dateCalibrLbl = QtWidgets.QLabel(self.tabMain)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.dateCalibrLbl.setFont(font)
        self.dateCalibrLbl.setObjectName("dateCalibrLbl")
        self.horizontalLayout_6.addWidget(self.dateCalibrLbl)
        self.horizontalLayout_12.addLayout(self.horizontalLayout_6)
        spacerItem = QtWidgets.QSpacerItem(248, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_12.addItem(spacerItem)
        self.applySetBtn = QtWidgets.QPushButton(self.tabMain)
        self.applySetBtn.setEnabled(True)
        self.applySetBtn.setObjectName("applySetBtn")
        self.horizontalLayout_12.addWidget(self.applySetBtn)
        self.gridLayout_4.addLayout(self.horizontalLayout_12, 0, 0, 1, 2)
        self.horizontalLayout_15 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_15.setObjectName("horizontalLayout_15")
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.groupBox_8 = QtWidgets.QGroupBox(self.tabMain)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox_8.sizePolicy().hasHeightForWidth())
        self.groupBox_8.setSizePolicy(sizePolicy)
        self.groupBox_8.setMaximumSize(QtCore.QSize(70, 16777215))
        self.groupBox_8.setObjectName("groupBox_8")
        self.gridLayout_10 = QtWidgets.QGridLayout(self.groupBox_8)
        self.gridLayout_10.setObjectName("gridLayout_10")
        self.testTimeLbl = QtWidgets.QLabel(self.groupBox_8)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.testTimeLbl.sizePolicy().hasHeightForWidth())
        self.testTimeLbl.setSizePolicy(sizePolicy)
        self.testTimeLbl.setMaximumSize(QtCore.QSize(50, 16777215))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.testTimeLbl.setFont(font)
        self.testTimeLbl.setObjectName("testTimeLbl")
        self.gridLayout_10.addWidget(self.testTimeLbl, 0, 0, 1, 1)
        self.horizontalLayout_7.addWidget(self.groupBox_8)
        self.startTestBtn = QtWidgets.QPushButton(self.tabMain)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.startTestBtn.sizePolicy().hasHeightForWidth())
        self.startTestBtn.setSizePolicy(sizePolicy)
        self.startTestBtn.setMaximumSize(QtCore.QSize(131, 41))
        self.startTestBtn.setObjectName("startTestBtn")
        self.horizontalLayout_7.addWidget(self.startTestBtn)
        self.horizontalLayout_15.addLayout(self.horizontalLayout_7)
        self.ConnectionBox = QtWidgets.QGroupBox(self.tabMain)
        self.ConnectionBox.setMaximumSize(QtCore.QSize(191, 67))
        self.ConnectionBox.setObjectName("ConnectionBox")
        self.gridLayout_7 = QtWidgets.QGridLayout(self.ConnectionBox)
        self.gridLayout_7.setObjectName("gridLayout_7")
        self.gridLayout_2 = QtWidgets.QGridLayout()
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.labelPort = QtWidgets.QLabel(self.ConnectionBox)
        self.labelPort.setObjectName("labelPort")
        self.gridLayout_2.addWidget(self.labelPort, 0, 0, 1, 1)
        self.labelBaud = QtWidgets.QLabel(self.ConnectionBox)
        self.labelBaud.setObjectName("labelBaud")
        self.gridLayout_2.addWidget(self.labelBaud, 1, 0, 1, 1)
        self.movie = QtWidgets.QLabel(self.ConnectionBox)
        self.movie.setMinimumSize(QtCore.QSize(36, 32))
        self.movie.setText("")
        self.movie.setObjectName("movie")
        self.gridLayout_2.addWidget(self.movie, 0, 2, 2, 1)
        self.portLbl = QtWidgets.QLabel(self.ConnectionBox)
        self.portLbl.setObjectName("portLbl")
        self.gridLayout_2.addWidget(self.portLbl, 0, 1, 1, 1)
        self.baudLbl = QtWidgets.QLabel(self.ConnectionBox)
        self.baudLbl.setObjectName("baudLbl")
        self.gridLayout_2.addWidget(self.baudLbl, 1, 1, 1, 1)
        self.gridLayout_7.addLayout(self.gridLayout_2, 0, 0, 1, 1)
        self.horizontalLayout_15.addWidget(self.ConnectionBox)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.currTestLbl = QtWidgets.QLabel(self.tabMain)
        self.currTestLbl.setMaximumSize(QtCore.QSize(199, 22))
        self.currTestLbl.setObjectName("currTestLbl")
        self.verticalLayout.addWidget(self.currTestLbl)
        self.TestPrBar = QtWidgets.QProgressBar(self.tabMain)
        self.TestPrBar.setMaximumSize(QtCore.QSize(199, 21))
        self.TestPrBar.setProperty("value", 24)
        self.TestPrBar.setObjectName("TestPrBar")
        self.verticalLayout.addWidget(self.TestPrBar)
        self.horizontalLayout_15.addLayout(self.verticalLayout)
        spacerItem1 = QtWidgets.QSpacerItem(168, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_15.addItem(spacerItem1)
        self.clrLogBtn = QtWidgets.QPushButton(self.tabMain)
        self.clrLogBtn.setMaximumSize(QtCore.QSize(81, 28))
        self.clrLogBtn.setObjectName("clrLogBtn")
        self.horizontalLayout_15.addWidget(self.clrLogBtn)
        self.gridLayout_4.addLayout(self.horizontalLayout_15, 3, 0, 1, 2)
        self.testsGroupBox = QtWidgets.QGroupBox(self.tabMain)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.testsGroupBox.sizePolicy().hasHeightForWidth())
        self.testsGroupBox.setSizePolicy(sizePolicy)
        self.testsGroupBox.setMinimumSize(QtCore.QSize(211, 181))
        self.testsGroupBox.setMaximumSize(QtCore.QSize(211, 181))
        self.testsGroupBox.setObjectName("testsGroupBox")
        self.checkGainTest = QtWidgets.QCheckBox(self.testsGroupBox)
        self.checkGainTest.setGeometry(QtCore.QRect(10, 23, 191, 16))
        self.checkGainTest.setMaximumSize(QtCore.QSize(191, 16777215))
        self.checkGainTest.setChecked(True)
        self.checkGainTest.setAutoExclusive(False)
        self.checkGainTest.setObjectName("checkGainTest")
        self.checkDsaTest = QtWidgets.QCheckBox(self.testsGroupBox)
        self.checkDsaTest.setGeometry(QtCore.QRect(10, 44, 191, 16))
        self.checkDsaTest.setMaximumSize(QtCore.QSize(191, 17))
        self.checkDsaTest.setChecked(True)
        self.checkDsaTest.setAutoExclusive(False)
        self.checkDsaTest.setObjectName("checkDsaTest")
        self.checkImTest = QtWidgets.QCheckBox(self.testsGroupBox)
        self.checkImTest.setGeometry(QtCore.QRect(10, 65, 191, 16))
        self.checkImTest.setMinimumSize(QtCore.QSize(191, 16))
        self.checkImTest.setMaximumSize(QtCore.QSize(191, 16777215))
        self.checkImTest.setChecked(True)
        self.checkImTest.setObjectName("checkImTest")
        self.checkBitAlarmTest = QtWidgets.QCheckBox(self.testsGroupBox)
        self.checkBitAlarmTest.setEnabled(True)
        self.checkBitAlarmTest.setGeometry(QtCore.QRect(10, 85, 191, 16))
        self.checkBitAlarmTest.setMaximumSize(QtCore.QSize(191, 16777215))
        self.checkBitAlarmTest.setChecked(True)
        self.checkBitAlarmTest.setObjectName("checkBitAlarmTest")
        self.checkRlossTest = QtWidgets.QCheckBox(self.testsGroupBox)
        self.checkRlossTest.setGeometry(QtCore.QRect(10, 127, 191, 16))
        self.checkRlossTest.setMaximumSize(QtCore.QSize(191, 16777215))
        self.checkRlossTest.setChecked(True)
        self.checkRlossTest.setObjectName("checkRlossTest")
        self.checkAlcTest = QtWidgets.QCheckBox(self.testsGroupBox)
        self.checkAlcTest.setGeometry(QtCore.QRect(10, 106, 191, 16))
        self.checkAlcTest.setMaximumSize(QtCore.QSize(191, 16777215))
        self.checkAlcTest.setChecked(True)
        self.checkAlcTest.setObjectName("checkAlcTest")
        self.gridLayout_4.addWidget(self.testsGroupBox, 2, 0, 1, 1)
        self.mainTabWidget.addTab(self.tabMain, "")
        self.tabJournal = QtWidgets.QWidget()
        self.tabJournal.setObjectName("tabJournal")
        self.gridLayout_14 = QtWidgets.QGridLayout(self.tabJournal)
        self.gridLayout_14.setObjectName("gridLayout_14")
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.label6 = QtWidgets.QLabel(self.tabJournal)
        self.label6.setMaximumSize(QtCore.QSize(31, 21))
        self.label6.setObjectName("label6")
        self.horizontalLayout_10.addWidget(self.label6)
        self.journalDateStart = QtWidgets.QDateEdit(self.tabJournal)
        self.journalDateStart.setMaximumSize(QtCore.QSize(81, 22))
        self.journalDateStart.setLocale(QtCore.QLocale(QtCore.QLocale.Hebrew, QtCore.QLocale.Israel))
        self.journalDateStart.setObjectName("journalDateStart")
        self.horizontalLayout_10.addWidget(self.journalDateStart)
        self.label7 = QtWidgets.QLabel(self.tabJournal)
        self.label7.setMaximumSize(QtCore.QSize(16, 21))
        self.label7.setObjectName("label7")
        self.horizontalLayout_10.addWidget(self.label7)
        self.journalDateStop = QtWidgets.QDateEdit(self.tabJournal)
        self.journalDateStop.setMaximumSize(QtCore.QSize(81, 21))
        self.journalDateStop.setLocale(QtCore.QLocale(QtCore.QLocale.Hebrew, QtCore.QLocale.Israel))
        self.journalDateStop.setObjectName("journalDateStop")
        self.horizontalLayout_10.addWidget(self.journalDateStop)
        self.journalUpdateBtn = QtWidgets.QPushButton(self.tabJournal)
        self.journalUpdateBtn.setMaximumSize(QtCore.QSize(91, 21))
        self.journalUpdateBtn.setObjectName("journalUpdateBtn")
        self.horizontalLayout_10.addWidget(self.journalUpdateBtn)
        self.label5 = QtWidgets.QLabel(self.tabJournal)
        self.label5.setMaximumSize(QtCore.QSize(31, 21))
        self.label5.setObjectName("label5")
        self.horizontalLayout_10.addWidget(self.label5)
        self.journalFilter = QtWidgets.QLineEdit(self.tabJournal)
        self.journalFilter.setMaximumSize(QtCore.QSize(111, 20))
        self.journalFilter.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.journalFilter.setText("")
        self.journalFilter.setMaxLength(16)
        self.journalFilter.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.journalFilter.setObjectName("journalFilter")
        self.horizontalLayout_10.addWidget(self.journalFilter)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_10.addItem(spacerItem2)
        self.gridLayout_14.addLayout(self.horizontalLayout_10, 0, 0, 1, 1)
        self.tableJournal = QtWidgets.QTableWidget(self.tabJournal)
        self.tableJournal.viewport().setProperty("cursor", QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.tableJournal.setMouseTracking(True)
        self.tableJournal.setFocusPolicy(QtCore.Qt.WheelFocus)
        self.tableJournal.setToolTip("")
        self.tableJournal.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.tableJournal.setSelectionMode(QtWidgets.QAbstractItemView.SingleSelection)
        self.tableJournal.setObjectName("tableJournal")
        self.tableJournal.setColumnCount(16)
        self.tableJournal.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tableJournal.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableJournal.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableJournal.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableJournal.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableJournal.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableJournal.setHorizontalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableJournal.setHorizontalHeaderItem(6, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableJournal.setHorizontalHeaderItem(7, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableJournal.setHorizontalHeaderItem(8, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableJournal.setHorizontalHeaderItem(9, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableJournal.setHorizontalHeaderItem(10, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableJournal.setHorizontalHeaderItem(11, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableJournal.setHorizontalHeaderItem(12, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableJournal.setHorizontalHeaderItem(13, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableJournal.setHorizontalHeaderItem(14, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableJournal.setHorizontalHeaderItem(15, item)
        self.tableJournal.horizontalHeader().setDefaultSectionSize(71)
        self.gridLayout_14.addWidget(self.tableJournal, 1, 0, 1, 1)
        self.horizontalLayout_11 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_11.setObjectName("horizontalLayout_11")
        self.groupBox = QtWidgets.QGroupBox(self.tabJournal)
        self.groupBox.setMaximumSize(QtCore.QSize(91, 81))
        self.groupBox.setObjectName("groupBox")
        self.gridLayout_12 = QtWidgets.QGridLayout(self.groupBox)
        self.gridLayout_12.setObjectName("gridLayout_12")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout()
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.logoCobhamRadio = QtWidgets.QRadioButton(self.groupBox)
        self.logoCobhamRadio.setChecked(True)
        self.logoCobhamRadio.setObjectName("logoCobhamRadio")
        self.verticalLayout_4.addWidget(self.logoCobhamRadio)
        self.logoAxellRadio = QtWidgets.QRadioButton(self.groupBox)
        self.logoAxellRadio.setChecked(False)
        self.logoAxellRadio.setObjectName("logoAxellRadio")
        self.verticalLayout_4.addWidget(self.logoAxellRadio)
        self.gridLayout_12.addLayout(self.verticalLayout_4, 0, 0, 1, 1)
        self.horizontalLayout_11.addWidget(self.groupBox)
        self.groupBox_2 = QtWidgets.QGroupBox(self.tabJournal)
        self.groupBox_2.setMaximumSize(QtCore.QSize(141, 81))
        self.groupBox_2.setObjectName("groupBox_2")
        self.gridLayout_13 = QtWidgets.QGridLayout(self.groupBox_2)
        self.gridLayout_13.setObjectName("gridLayout_13")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.reportTemplateCombo = QtWidgets.QComboBox(self.groupBox_2)
        self.reportTemplateCombo.setObjectName("reportTemplateCombo")
        self.verticalLayout_3.addWidget(self.reportTemplateCombo)
        self.printReportBtn = QtWidgets.QPushButton(self.groupBox_2)
        self.printReportBtn.setObjectName("printReportBtn")
        self.verticalLayout_3.addWidget(self.printReportBtn)
        self.gridLayout_13.addLayout(self.verticalLayout_3, 0, 0, 1, 1)
        self.horizontalLayout_11.addWidget(self.groupBox_2)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_11.addItem(spacerItem3)
        self.gridLayout_14.addLayout(self.horizontalLayout_11, 2, 0, 1, 1)
        self.mainTabWidget.addTab(self.tabJournal, "")
        self.tabSettings = QtWidgets.QWidget()
        self.tabSettings.setObjectName("tabSettings")
        self.instrumentsGroupBox = QtWidgets.QGroupBox(self.tabSettings)
        self.instrumentsGroupBox.setGeometry(QtCore.QRect(10, 10, 541, 171))
        self.instrumentsGroupBox.setObjectName("instrumentsGroupBox")
        self.instrAddrCombo = QtWidgets.QComboBox(self.instrumentsGroupBox)
        self.instrAddrCombo.setGeometry(QtCore.QRect(10, 110, 191, 21))
        self.instrAddrCombo.setMouseTracking(True)
        self.instrAddrCombo.setObjectName("instrAddrCombo")
        self.setSaRadio = QtWidgets.QRadioButton(self.instrumentsGroupBox)
        self.setSaRadio.setGeometry(QtCore.QRect(10, 20, 50, 20))
        self.setSaRadio.setMinimumSize(QtCore.QSize(50, 20))
        self.setSaRadio.setChecked(True)
        self.setSaRadio.setObjectName("setSaRadio")
        self.setGenRadio = QtWidgets.QRadioButton(self.instrumentsGroupBox)
        self.setGenRadio.setGeometry(QtCore.QRect(10, 50, 51, 17))
        self.setGenRadio.setMinimumSize(QtCore.QSize(50, 0))
        self.setGenRadio.setObjectName("setGenRadio")
        self.label0 = QtWidgets.QLabel(self.instrumentsGroupBox)
        self.label0.setGeometry(QtCore.QRect(210, 110, 51, 20))
        self.label0.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label0.setObjectName("label0")
        self.label1 = QtWidgets.QLabel(self.instrumentsGroupBox)
        self.label1.setGeometry(QtCore.QRect(310, 110, 61, 20))
        self.label1.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label1.setObjectName("label1")
        self.saAtten = QtWidgets.QLineEdit(self.instrumentsGroupBox)
        self.saAtten.setGeometry(QtCore.QRect(270, 110, 31, 20))
        self.saAtten.setAlignment(QtCore.Qt.AlignCenter)
        self.saAtten.setObjectName("saAtten")
        self.genAtten = QtWidgets.QLineEdit(self.instrumentsGroupBox)
        self.genAtten.setGeometry(QtCore.QRect(380, 110, 31, 20))
        self.genAtten.setAlignment(QtCore.Qt.AlignCenter)
        self.genAtten.setObjectName("genAtten")
        self.setNaRadio = QtWidgets.QRadioButton(self.instrumentsGroupBox)
        self.setNaRadio.setGeometry(QtCore.QRect(10, 80, 51, 20))
        self.setNaRadio.setObjectName("setNaRadio")
        self.setInstrBtn = QtWidgets.QPushButton(self.instrumentsGroupBox)
        self.setInstrBtn.setGeometry(QtCore.QRect(110, 140, 91, 23))
        self.setInstrBtn.setObjectName("setInstrBtn")
        self.label21 = QtWidgets.QLabel(self.instrumentsGroupBox)
        self.label21.setGeometry(QtCore.QRect(420, 110, 71, 20))
        self.label21.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label21.setObjectName("label21")
        self.naAtten1 = QtWidgets.QLineEdit(self.instrumentsGroupBox)
        self.naAtten1.setGeometry(QtCore.QRect(500, 110, 31, 20))
        self.naAtten1.setAlignment(QtCore.Qt.AlignCenter)
        self.naAtten1.setObjectName("naAtten1")
        self.line = QtWidgets.QFrame(self.instrumentsGroupBox)
        self.line.setGeometry(QtCore.QRect(60, 40, 471, 16))
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.line_2 = QtWidgets.QFrame(self.instrumentsGroupBox)
        self.line_2.setGeometry(QtCore.QRect(60, 70, 471, 16))
        self.line_2.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.updateInstrBtn = QtWidgets.QPushButton(self.instrumentsGroupBox)
        self.updateInstrBtn.setGeometry(QtCore.QRect(10, 140, 91, 23))
        self.updateInstrBtn.setObjectName("updateInstrBtn")
        self.saStat = QtWidgets.QLabel(self.instrumentsGroupBox)
        self.saStat.setGeometry(QtCore.QRect(60, 20, 20, 21))
        self.saStat.setMinimumSize(QtCore.QSize(20, 20))
        self.saStat.setObjectName("saStat")
        self.genStat = QtWidgets.QLabel(self.instrumentsGroupBox)
        self.genStat.setGeometry(QtCore.QRect(60, 50, 21, 21))
        self.genStat.setMinimumSize(QtCore.QSize(20, 20))
        self.genStat.setObjectName("genStat")
        self.naStat = QtWidgets.QLabel(self.instrumentsGroupBox)
        self.naStat.setGeometry(QtCore.QRect(60, 80, 21, 21))
        self.naStat.setObjectName("naStat")
        self.label2_2 = QtWidgets.QLabel(self.instrumentsGroupBox)
        self.label2_2.setGeometry(QtCore.QRect(420, 140, 71, 20))
        self.label2_2.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label2_2.setObjectName("label2_2")
        self.naAtten2 = QtWidgets.QLineEdit(self.instrumentsGroupBox)
        self.naAtten2.setGeometry(QtCore.QRect(500, 140, 31, 20))
        self.naAtten2.setAlignment(QtCore.Qt.AlignCenter)
        self.naAtten2.setObjectName("naAtten2")
        self.currSaLbl = QtWidgets.QLabel(self.instrumentsGroupBox)
        self.currSaLbl.setGeometry(QtCore.QRect(101, 21, 111, 20))
        self.currSaLbl.setMinimumSize(QtCore.QSize(110, 20))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(9)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(9)
        self.currSaLbl.setFont(font)
        self.currSaLbl.setStyleSheet("font: 75 9pt \"Times New Roman\";")
        self.currSaLbl.setTextFormat(QtCore.Qt.RichText)
        self.currSaLbl.setObjectName("currSaLbl")
        self.currSaNameLbl = QtWidgets.QLabel(self.instrumentsGroupBox)
        self.currSaNameLbl.setGeometry(QtCore.QRect(220, 21, 300, 20))
        self.currSaNameLbl.setMinimumSize(QtCore.QSize(300, 20))
        self.currSaNameLbl.setStyleSheet("font: 75 9pt \"Times New Roman\";")
        self.currSaNameLbl.setTextFormat(QtCore.Qt.RichText)
        self.currSaNameLbl.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.currSaNameLbl.setObjectName("currSaNameLbl")
        self.currGenNameLbl = QtWidgets.QLabel(self.instrumentsGroupBox)
        self.currGenNameLbl.setGeometry(QtCore.QRect(220, 51, 300, 20))
        self.currGenNameLbl.setMinimumSize(QtCore.QSize(300, 20))
        self.currGenNameLbl.setStyleSheet("font: 75 9pt \"Times New Roman\";")
        self.currGenNameLbl.setTextFormat(QtCore.Qt.RichText)
        self.currGenNameLbl.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.currGenNameLbl.setObjectName("currGenNameLbl")
        self.currGenLbl = QtWidgets.QLabel(self.instrumentsGroupBox)
        self.currGenLbl.setGeometry(QtCore.QRect(101, 51, 110, 20))
        self.currGenLbl.setMinimumSize(QtCore.QSize(110, 20))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(9)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(9)
        self.currGenLbl.setFont(font)
        self.currGenLbl.setStyleSheet("font: 75 9pt \"Times New Roman\";")
        self.currGenLbl.setTextFormat(QtCore.Qt.RichText)
        self.currGenLbl.setObjectName("currGenLbl")
        self.currNaNameLbl = QtWidgets.QLabel(self.instrumentsGroupBox)
        self.currNaNameLbl.setGeometry(QtCore.QRect(220, 81, 300, 20))
        self.currNaNameLbl.setMinimumSize(QtCore.QSize(300, 20))
        self.currNaNameLbl.setStyleSheet("font: 75 9pt \"Times New Roman\";")
        self.currNaNameLbl.setTextFormat(QtCore.Qt.RichText)
        self.currNaNameLbl.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.currNaNameLbl.setObjectName("currNaNameLbl")
        self.currNaLbl = QtWidgets.QLabel(self.instrumentsGroupBox)
        self.currNaLbl.setGeometry(QtCore.QRect(101, 81, 110, 20))
        self.currNaLbl.setMinimumSize(QtCore.QSize(110, 20))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(9)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(9)
        self.currNaLbl.setFont(font)
        self.currNaLbl.setStyleSheet("font: 75 9pt \"Times New Roman\";")
        self.currNaLbl.setTextFormat(QtCore.Qt.RichText)
        self.currNaLbl.setObjectName("currNaLbl")
        self.calibrationGroupBox = QtWidgets.QGroupBox(self.tabSettings)
        self.calibrationGroupBox.setGeometry(QtCore.QRect(560, 60, 241, 121))
        self.calibrationGroupBox.setObjectName("calibrationGroupBox")
        self.calAllBands = QtWidgets.QCheckBox(self.calibrationGroupBox)
        self.calAllBands.setGeometry(QtCore.QRect(20, 20, 111, 17))
        self.calAllBands.setMinimumSize(QtCore.QSize(111, 17))
        self.calAllBands.setMaximumSize(QtCore.QSize(111, 17))
        self.calAllBands.setObjectName("calAllBands")
        self.calibrationBtn = QtWidgets.QPushButton(self.calibrationGroupBox)
        self.calibrationBtn.setGeometry(QtCore.QRect(150, 70, 75, 31))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.calibrationBtn.sizePolicy().hasHeightForWidth())
        self.calibrationBtn.setSizePolicy(sizePolicy)
        self.calibrationBtn.setMinimumSize(QtCore.QSize(75, 31))
        self.calibrationBtn.setMaximumSize(QtCore.QSize(75, 31))
        self.calibrationBtn.setObjectName("calibrationBtn")
        self.label51 = QtWidgets.QLabel(self.calibrationGroupBox)
        self.label51.setGeometry(QtCore.QRect(21, 77, 28, 20))
        self.label51.setMinimumSize(QtCore.QSize(28, 20))
        self.label51.setMaximumSize(QtCore.QSize(28, 20))
        self.label51.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label51.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label51.setObjectName("label51")
        self.label71 = QtWidgets.QLabel(self.calibrationGroupBox)
        self.label71.setGeometry(QtCore.QRect(115, 77, 20, 20))
        self.label71.setMinimumSize(QtCore.QSize(20, 20))
        self.label71.setMaximumSize(QtCore.QSize(20, 20))
        self.label71.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label71.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label71.setObjectName("label71")
        self.label61 = QtWidgets.QLabel(self.calibrationGroupBox)
        self.label61.setGeometry(QtCore.QRect(115, 51, 20, 20))
        self.label61.setMinimumSize(QtCore.QSize(20, 20))
        self.label61.setMaximumSize(QtCore.QSize(20, 20))
        self.label61.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label61.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label61.setObjectName("label61")
        self.label41 = QtWidgets.QLabel(self.calibrationGroupBox)
        self.label41.setGeometry(QtCore.QRect(21, 51, 28, 20))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label41.sizePolicy().hasHeightForWidth())
        self.label41.setSizePolicy(sizePolicy)
        self.label41.setMinimumSize(QtCore.QSize(28, 20))
        self.label41.setMaximumSize(QtCore.QSize(28, 20))
        self.label41.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label41.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label41.setObjectName("label41")
        self.calibrStop = QtWidgets.QLineEdit(self.calibrationGroupBox)
        self.calibrStop.setGeometry(QtCore.QRect(55, 77, 54, 20))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.calibrStop.sizePolicy().hasHeightForWidth())
        self.calibrStop.setSizePolicy(sizePolicy)
        self.calibrStop.setMinimumSize(QtCore.QSize(54, 20))
        self.calibrStop.setMaximumSize(QtCore.QSize(54, 20))
        self.calibrStop.setMaxLength(4)
        self.calibrStop.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.calibrStop.setObjectName("calibrStop")
        self.calibrStart = QtWidgets.QLineEdit(self.calibrationGroupBox)
        self.calibrStart.setGeometry(QtCore.QRect(55, 51, 54, 20))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.calibrStart.sizePolicy().hasHeightForWidth())
        self.calibrStart.setSizePolicy(sizePolicy)
        self.calibrStart.setMinimumSize(QtCore.QSize(54, 20))
        self.calibrStart.setMaximumSize(QtCore.QSize(54, 20))
        self.calibrStart.setMaxLength(4)
        self.calibrStart.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.calibrStart.setObjectName("calibrStart")
        self.clearCalBtn = QtWidgets.QPushButton(self.calibrationGroupBox)
        self.clearCalBtn.setGeometry(QtCore.QRect(150, 32, 77, 31))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.clearCalBtn.sizePolicy().hasHeightForWidth())
        self.clearCalBtn.setSizePolicy(sizePolicy)
        self.clearCalBtn.setMinimumSize(QtCore.QSize(77, 31))
        self.clearCalBtn.setMaximumSize(QtCore.QSize(77, 31))
        self.clearCalBtn.setObjectName("clearCalBtn")
        self.rfbAtrGroupBox = QtWidgets.QGroupBox(self.tabSettings)
        self.rfbAtrGroupBox.setGeometry(QtCore.QRect(560, 10, 241, 51))
        self.rfbAtrGroupBox.setObjectName("rfbAtrGroupBox")
        self.newRfbBtn = QtWidgets.QPushButton(self.rfbAtrGroupBox)
        self.newRfbBtn.setGeometry(QtCore.QRect(150, 20, 81, 23))
        self.newRfbBtn.setObjectName("newRfbBtn")
        self.editRfbCombo = QtWidgets.QComboBox(self.rfbAtrGroupBox)
        self.editRfbCombo.setGeometry(QtCore.QRect(10, 20, 131, 22))
        self.editRfbCombo.setObjectName("editRfbCombo")
        self.gainTestgroupBox = QtWidgets.QGroupBox(self.tabSettings)
        self.gainTestgroupBox.setGeometry(QtCore.QRect(10, 180, 71, 65))
        self.gainTestgroupBox.setMinimumSize(QtCore.QSize(70, 65))
        self.gainTestgroupBox.setObjectName("gainTestgroupBox")
        self.gainNA = QtWidgets.QRadioButton(self.gainTestgroupBox)
        self.gainNA.setGeometry(QtCore.QRect(10, 30, 57, 25))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.gainNA.sizePolicy().hasHeightForWidth())
        self.gainNA.setSizePolicy(sizePolicy)
        self.gainNA.setMinimumSize(QtCore.QSize(57, 25))
        self.gainNA.setMaximumSize(QtCore.QSize(57, 20))
        self.gainNA.setObjectName("gainNA")
        self.gainSA = QtWidgets.QRadioButton(self.gainTestgroupBox)
        self.gainSA.setGeometry(QtCore.QRect(10, 10, 56, 25))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.gainSA.sizePolicy().hasHeightForWidth())
        self.gainSA.setSizePolicy(sizePolicy)
        self.gainSA.setMinimumSize(QtCore.QSize(56, 25))
        self.gainSA.setMaximumSize(QtCore.QSize(56, 20))
        self.gainSA.setChecked(True)
        self.gainSA.setObjectName("gainSA")
        self.dsaGroupBox = QtWidgets.QGroupBox(self.tabSettings)
        self.dsaGroupBox.setGeometry(QtCore.QRect(90, 180, 71, 65))
        self.dsaGroupBox.setMinimumSize(QtCore.QSize(70, 65))
        self.dsaGroupBox.setObjectName("dsaGroupBox")
        self.testSetDsaShort = QtWidgets.QRadioButton(self.dsaGroupBox)
        self.testSetDsaShort.setGeometry(QtCore.QRect(10, 10, 48, 25))
        self.testSetDsaShort.setMinimumSize(QtCore.QSize(48, 25))
        self.testSetDsaShort.setChecked(True)
        self.testSetDsaShort.setObjectName("testSetDsaShort")
        self.testSetDsaFull = QtWidgets.QRadioButton(self.dsaGroupBox)
        self.testSetDsaFull.setGeometry(QtCore.QRect(10, 30, 37, 25))
        self.testSetDsaFull.setMinimumSize(QtCore.QSize(37, 25))
        self.testSetDsaFull.setObjectName("testSetDsaFull")
        self.mainTabWidget.addTab(self.tabSettings, "")
        self.gridLayout_8.addWidget(self.mainTabWidget, 0, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menuBar = QtWidgets.QMenuBar(MainWindow)
        self.menuBar.setGeometry(QtCore.QRect(0, 0, 910, 20))
        self.menuBar.setObjectName("menuBar")
        self.menuFile = QtWidgets.QMenu(self.menuBar)
        self.menuFile.setObjectName("menuFile")
        self.menuSettings = QtWidgets.QMenu(self.menuBar)
        self.menuSettings.setObjectName("menuSettings")
        MainWindow.setMenuBar(self.menuBar)
        self.menuExit = QtWidgets.QAction(MainWindow)
        self.menuExit.setObjectName("menuExit")
        self.menuSelectUser = QtWidgets.QAction(MainWindow)
        self.menuSelectUser.setObjectName("menuSelectUser")
        self.menuTestSettings = QtWidgets.QAction(MainWindow)
        self.menuTestSettings.setObjectName("menuTestSettings")
        self.menuComPort = QtWidgets.QAction(MainWindow)
        self.menuComPort.setObjectName("menuComPort")
        self.menuFile.addAction(self.menuSelectUser)
        self.menuFile.addAction(self.menuExit)
        self.menuSettings.addAction(self.menuComPort)
        self.menuSettings.addAction(self.menuTestSettings)
        self.menuBar.addAction(self.menuFile.menuAction())
        self.menuBar.addAction(self.menuSettings.menuAction())

        self.retranslateUi(MainWindow)
        self.mainTabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
        MainWindow.setTabOrder(self.listLog, self.clrLogBtn)
        MainWindow.setTabOrder(self.clrLogBtn, self.startTestBtn)
        MainWindow.setTabOrder(self.startTestBtn, self.rfbTypeCombo)
        MainWindow.setTabOrder(self.rfbTypeCombo, self.checkGainTest)
        MainWindow.setTabOrder(self.checkGainTest, self.checkDsaTest)
        MainWindow.setTabOrder(self.checkDsaTest, self.checkBitAlarmTest)
        MainWindow.setTabOrder(self.checkBitAlarmTest, self.checkImTest)
        MainWindow.setTabOrder(self.checkImTest, self.rfbSN)
        MainWindow.setTabOrder(self.rfbSN, self.tableResult)
        MainWindow.setTabOrder(self.tableResult, self.tableJournal)
        MainWindow.setTabOrder(self.tableJournal, self.journalUpdateBtn)
        MainWindow.setTabOrder(self.journalUpdateBtn, self.journalDateStart)
        MainWindow.setTabOrder(self.journalDateStart, self.journalDateStop)
        MainWindow.setTabOrder(self.journalDateStop, self.printReportBtn)
        MainWindow.setTabOrder(self.printReportBtn, self.journalFilter)
        MainWindow.setTabOrder(self.journalFilter, self.logoAxellRadio)
        MainWindow.setTabOrder(self.logoAxellRadio, self.logoCobhamRadio)
        MainWindow.setTabOrder(self.logoCobhamRadio, self.reportTemplateCombo)
        MainWindow.setTabOrder(self.reportTemplateCombo, self.instrAddrCombo)
        MainWindow.setTabOrder(self.instrAddrCombo, self.setSaRadio)
        MainWindow.setTabOrder(self.setSaRadio, self.setGenRadio)
        MainWindow.setTabOrder(self.setGenRadio, self.saAtten)
        MainWindow.setTabOrder(self.saAtten, self.genAtten)
        MainWindow.setTabOrder(self.genAtten, self.saAtten)
        MainWindow.setTabOrder(self.saAtten, self.setNaRadio)
        MainWindow.setTabOrder(self.setNaRadio, self.setInstrBtn)
        MainWindow.setTabOrder(self.setInstrBtn, self.naAtten1)
        MainWindow.setTabOrder(self.naAtten1, self.testSetDsaFull)
        MainWindow.setTabOrder(self.testSetDsaFull, self.testSetDsaShort)
        MainWindow.setTabOrder(self.testSetDsaShort, self.calibrationBtn)
        MainWindow.setTabOrder(self.calibrationBtn, self.clearCalBtn)
        MainWindow.setTabOrder(self.clearCalBtn, self.calAllBands)
        MainWindow.setTabOrder(self.calAllBands, self.newRfbBtn)
        MainWindow.setTabOrder(self.newRfbBtn, self.editRfbCombo)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        self.logGroupBox.setTitle(_translate("MainWindow", "Log"))
        self.groupBox_3.setTitle(_translate("MainWindow", "Test settings"))
        item = self.tableSettings.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Settings"))
        item = self.tableSettings.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Value"))
        self.groupBox_7.setTitle(_translate("MainWindow", "Result"))
        item = self.tableResult.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Test name"))
        item = self.tableResult.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Dl/Ul"))
        item = self.tableResult.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "Min"))
        item = self.tableResult.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "Current"))
        item = self.tableResult.horizontalHeaderItem(4)
        item.setText(_translate("MainWindow", "Max"))
        item = self.tableResult.horizontalHeaderItem(5)
        item.setText(_translate("MainWindow", "Result"))
        self.label_9.setText(_translate("MainWindow", "RFB type:"))
        self.label2.setText(_translate("MainWindow", "RFB SN:"))
        self.label3_2.setText(_translate("MainWindow", "Calibration:"))
        self.calibrLbl.setText(_translate("MainWindow", "none"))
        self.label4.setText(_translate("MainWindow", "Date:"))
        self.dateCalibrLbl.setText(_translate("MainWindow", "none"))
        self.applySetBtn.setText(_translate("MainWindow", "Apply SetFile"))
        self.groupBox_8.setTitle(_translate("MainWindow", "Test timer"))
        self.testTimeLbl.setText(_translate("MainWindow", "0:00:00"))
        self.startTestBtn.setText(_translate("MainWindow", "Start"))
        self.ConnectionBox.setTitle(_translate("MainWindow", "Connection"))
        self.labelPort.setText(_translate("MainWindow", "Port :"))
        self.labelBaud.setText(_translate("MainWindow", "Baud:"))
        self.portLbl.setText(_translate("MainWindow", "port"))
        self.baudLbl.setText(_translate("MainWindow", "baud"))
        self.currTestLbl.setText(_translate("MainWindow", "none"))
        self.clrLogBtn.setText(_translate("MainWindow", "Clear Log"))
        self.testsGroupBox.setTitle(_translate("MainWindow", "Tests"))
        self.checkGainTest.setText(_translate("MainWindow", "Gain and flatness"))
        self.checkDsaTest.setText(_translate("MainWindow", "DSA"))
        self.checkImTest.setText(_translate("MainWindow", "Intermodulation"))
        self.checkBitAlarmTest.setText(_translate("MainWindow", "BIT alarm"))
        self.checkRlossTest.setText(_translate("MainWindow", "Return loss"))
        self.checkAlcTest.setText(_translate("MainWindow", "ALC"))
        self.mainTabWidget.setTabText(self.mainTabWidget.indexOf(self.tabMain), _translate("MainWindow", "Main"))
        self.label6.setText(_translate("MainWindow", "From:"))
        self.journalDateStart.setDisplayFormat(_translate("MainWindow", "dd.MM.yyyy"))
        self.label7.setText(_translate("MainWindow", "To:"))
        self.journalDateStop.setDisplayFormat(_translate("MainWindow", "dd.MM.yyyy"))
        self.journalUpdateBtn.setText(_translate("MainWindow", "Update"))
        self.label5.setText(_translate("MainWindow", "Filter:"))
        self.tableJournal.setSortingEnabled(False)
        item = self.tableJournal.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "RFB type"))
        item = self.tableJournal.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "DSA 1"))
        item = self.tableJournal.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "Date test"))
        item = self.tableJournal.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "Band"))
        item = self.tableJournal.horizontalHeaderItem(4)
        item.setText(_translate("MainWindow", "Gain"))
        item = self.tableJournal.horizontalHeaderItem(5)
        item.setText(_translate("MainWindow", "Flatness"))
        item = self.tableJournal.horizontalHeaderItem(6)
        item.setText(_translate("MainWindow", "New Column"))
        item = self.tableJournal.horizontalHeaderItem(7)
        item.setText(_translate("MainWindow", "DSA 2"))
        item = self.tableJournal.horizontalHeaderItem(8)
        item.setText(_translate("MainWindow", "DSA 3"))
        item = self.tableJournal.horizontalHeaderItem(9)
        item.setText(_translate("MainWindow", "IMod"))
        item = self.tableJournal.horizontalHeaderItem(10)
        item.setText(_translate("MainWindow", "BIT"))
        item = self.tableJournal.horizontalHeaderItem(11)
        item.setText(_translate("MainWindow", "ALC In"))
        item = self.tableJournal.horizontalHeaderItem(12)
        item.setText(_translate("MainWindow", "ALC Out"))
        item = self.tableJournal.horizontalHeaderItem(13)
        item.setText(_translate("MainWindow", "RLoss"))
        item = self.tableJournal.horizontalHeaderItem(14)
        item.setText(_translate("MainWindow", "Status"))
        item = self.tableJournal.horizontalHeaderItem(15)
        item.setText(_translate("MainWindow", "User"))
        self.groupBox.setTitle(_translate("MainWindow", "Logo"))
        self.logoCobhamRadio.setText(_translate("MainWindow", "Cobham"))
        self.logoAxellRadio.setText(_translate("MainWindow", "Axell"))
        self.groupBox_2.setTitle(_translate("MainWindow", "Report"))
        self.printReportBtn.setText(_translate("MainWindow", "Print report"))
        self.mainTabWidget.setTabText(self.mainTabWidget.indexOf(self.tabJournal), _translate("MainWindow", "Journal"))
        self.instrumentsGroupBox.setTitle(_translate("MainWindow", "Instruments"))
        self.setSaRadio.setText(_translate("MainWindow", "SA:"))
        self.setGenRadio.setText(_translate("MainWindow", "GEN:"))
        self.label0.setText(_translate("MainWindow", "SA atten.:"))
        self.label1.setText(_translate("MainWindow", "GEN atten.:"))
        self.setNaRadio.setText(_translate("MainWindow", "NA:"))
        self.setInstrBtn.setText(_translate("MainWindow", "Set"))
        self.label21.setText(_translate("MainWindow", "NA atten. P1:"))
        self.updateInstrBtn.setText(_translate("MainWindow", "Update"))
        self.saStat.setText(_translate("MainWindow", "saStat"))
        self.genStat.setText(_translate("MainWindow", "genStat"))
        self.naStat.setText(_translate("MainWindow", "naStat"))
        self.label2_2.setText(_translate("MainWindow", "NA atten. P2:"))
        self.currSaLbl.setText(_translate("MainWindow", "currSaLbl"))
        self.currSaNameLbl.setText(_translate("MainWindow", "currSaNameLbl"))
        self.currGenNameLbl.setText(_translate("MainWindow", "currGenNameLbl"))
        self.currGenLbl.setText(_translate("MainWindow", "currGenLbl"))
        self.currNaNameLbl.setText(_translate("MainWindow", "currNaNameLbl"))
        self.currNaLbl.setText(_translate("MainWindow", "currNaLbl"))
        self.calibrationGroupBox.setTitle(_translate("MainWindow", "Calibration"))
        self.calAllBands.setText(_translate("MainWindow", "Calibtate all bands"))
        self.calibrationBtn.setText(_translate("MainWindow", "Calibration"))
        self.label51.setText(_translate("MainWindow", "Stop:"))
        self.label71.setText(_translate("MainWindow", "MHz"))
        self.label61.setText(_translate("MainWindow", "MHz"))
        self.label41.setText(_translate("MainWindow", "Start:"))
        self.clearCalBtn.setText(_translate("MainWindow", "Clear cal.table"))
        self.rfbAtrGroupBox.setTitle(_translate("MainWindow", "RFB ATR settings"))
        self.newRfbBtn.setText(_translate("MainWindow", "New/Edit"))
        self.gainTestgroupBox.setTitle(_translate("MainWindow", "Gain test"))
        self.gainNA.setText(_translate("MainWindow", "use NA"))
        self.gainSA.setText(_translate("MainWindow", "use SA"))
        self.dsaGroupBox.setTitle(_translate("MainWindow", "DSA"))
        self.testSetDsaShort.setText(_translate("MainWindow", "short"))
        self.testSetDsaFull.setText(_translate("MainWindow", "full"))
        self.mainTabWidget.setTabText(self.mainTabWidget.indexOf(self.tabSettings), _translate("MainWindow", "Settings"))
        self.menuFile.setTitle(_translate("MainWindow", "File"))
        self.menuSettings.setTitle(_translate("MainWindow", "Settings"))
        self.menuExit.setText(_translate("MainWindow", "Exit"))
        self.menuSelectUser.setText(_translate("MainWindow", "Select user"))
        self.menuTestSettings.setText(_translate("MainWindow", "Instrument settings"))
        self.menuComPort.setText(_translate("MainWindow", "COM port"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())

