# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainwindow.ui'
#
# Created: Sun Feb 11 14:55:00 2018
#      by: PyQt5 UI code generator 5.2.1
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.setWindowModality(QtCore.Qt.ApplicationModal)
        MainWindow.resize(840, 700)
        MainWindow.setMinimumSize(QtCore.QSize(840, 700))
        MainWindow.setMaximumSize(QtCore.QSize(5000, 5000))
        MainWindow.setWindowTitle("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("../Img/ico32_pgn_icon.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.mainTabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.mainTabWidget.setGeometry(QtCore.QRect(10, 10, 821, 651))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(100)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.mainTabWidget.sizePolicy().hasHeightForWidth())
        self.mainTabWidget.setSizePolicy(sizePolicy)
        self.mainTabWidget.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.mainTabWidget.setObjectName("mainTabWidget")
        self.tabMain = QtWidgets.QWidget()
        self.tabMain.setObjectName("tabMain")
        self.rfbTypeCombo = QtWidgets.QComboBox(self.tabMain)
        self.rfbTypeCombo.setGeometry(QtCore.QRect(80, 20, 111, 22))
        self.rfbTypeCombo.setObjectName("rfbTypeCombo")
        self.logGroupBox = QtWidgets.QGroupBox(self.tabMain)
        self.logGroupBox.setGeometry(QtCore.QRect(199, 350, 601, 211))
        self.logGroupBox.setObjectName("logGroupBox")
        self.listLog = QtWidgets.QListWidget(self.logGroupBox)
        self.listLog.setGeometry(QtCore.QRect(10, 20, 581, 181))
        self.listLog.setAutoFillBackground(False)
        self.listLog.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.listLog.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOn)
        self.listLog.setAutoScroll(True)
        self.listLog.setAutoScrollMargin(16)
        self.listLog.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.listLog.setTabKeyNavigation(False)
        self.listLog.setProperty("showDropIndicator", False)
        self.listLog.setDragDropMode(QtWidgets.QAbstractItemView.DragOnly)
        self.listLog.setAlternatingRowColors(False)
        self.listLog.setSelectionMode(QtWidgets.QAbstractItemView.NoSelection)
        self.listLog.setVerticalScrollMode(QtWidgets.QAbstractItemView.ScrollPerItem)
        self.listLog.setMovement(QtWidgets.QListView.Free)
        self.listLog.setFlow(QtWidgets.QListView.TopToBottom)
        self.listLog.setObjectName("listLog")
        self.clrLogBtn = QtWidgets.QPushButton(self.tabMain)
        self.clrLogBtn.setGeometry(QtCore.QRect(720, 570, 81, 28))
        self.clrLogBtn.setObjectName("clrLogBtn")
        self.label_9 = QtWidgets.QLabel(self.tabMain)
        self.label_9.setGeometry(QtCore.QRect(10, 20, 46, 13))
        self.label_9.setObjectName("label_9")
        self.startTestBtn = QtWidgets.QPushButton(self.tabMain)
        self.startTestBtn.setGeometry(QtCore.QRect(90, 520, 101, 31))
        self.startTestBtn.setObjectName("startTestBtn")
        self.testsGroupBox = QtWidgets.QGroupBox(self.tabMain)
        self.testsGroupBox.setGeometry(QtCore.QRect(0, 380, 191, 131))
        self.testsGroupBox.setObjectName("testsGroupBox")
        self.checkAlcTest = QtWidgets.QCheckBox(self.testsGroupBox)
        self.checkAlcTest.setGeometry(QtCore.QRect(10, 110, 70, 17))
        self.checkAlcTest.setChecked(True)
        self.checkAlcTest.setObjectName("checkAlcTest")
        self.checkGainTest = QtWidgets.QCheckBox(self.testsGroupBox)
        self.checkGainTest.setGeometry(QtCore.QRect(10, 30, 111, 17))
        self.checkGainTest.setChecked(True)
        self.checkGainTest.setAutoExclusive(False)
        self.checkGainTest.setObjectName("checkGainTest")
        self.checkDsaTest = QtWidgets.QCheckBox(self.testsGroupBox)
        self.checkDsaTest.setGeometry(QtCore.QRect(10, 50, 70, 17))
        self.checkDsaTest.setChecked(True)
        self.checkDsaTest.setAutoExclusive(False)
        self.checkDsaTest.setObjectName("checkDsaTest")
        self.checkBitAlarmTest = QtWidgets.QCheckBox(self.testsGroupBox)
        self.checkBitAlarmTest.setEnabled(True)
        self.checkBitAlarmTest.setGeometry(QtCore.QRect(10, 90, 70, 17))
        self.checkBitAlarmTest.setChecked(True)
        self.checkBitAlarmTest.setObjectName("checkBitAlarmTest")
        self.checkImTest = QtWidgets.QCheckBox(self.testsGroupBox)
        self.checkImTest.setGeometry(QtCore.QRect(10, 70, 101, 17))
        self.checkImTest.setChecked(True)
        self.checkImTest.setObjectName("checkImTest")
        self.label2 = QtWidgets.QLabel(self.tabMain)
        self.label2.setGeometry(QtCore.QRect(10, 50, 46, 13))
        self.label2.setObjectName("label2")
        self.rfbSN = QtWidgets.QLineEdit(self.tabMain)
        self.rfbSN.setGeometry(QtCore.QRect(80, 50, 113, 20))
        self.rfbSN.setText("")
        self.rfbSN.setMaxLength(10)
        self.rfbSN.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.rfbSN.setObjectName("rfbSN")
        self.tableSettings = QtWidgets.QTableWidget(self.tabMain)
        self.tableSettings.setGeometry(QtCore.QRect(10, 80, 181, 301))
        self.tableSettings.setMaximumSize(QtCore.QSize(181, 900))
        self.tableSettings.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.tableSettings.setAutoScroll(True)
        self.tableSettings.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.tableSettings.setRowCount(0)
        self.tableSettings.setColumnCount(2)
        self.tableSettings.setObjectName("tableSettings")
        item = QtWidgets.QTableWidgetItem()
        self.tableSettings.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableSettings.setHorizontalHeaderItem(1, item)
        self.tableSettings.verticalHeader().setVisible(False)
        self.tableSettings.verticalHeader().setHighlightSections(True)
        self.groupBox_7 = QtWidgets.QGroupBox(self.tabMain)
        self.groupBox_7.setGeometry(QtCore.QRect(200, 20, 601, 331))
        self.groupBox_7.setObjectName("groupBox_7")
        self.tableResult = QtWidgets.QTableWidget(self.groupBox_7)
        self.tableResult.setEnabled(True)
        self.tableResult.setGeometry(QtCore.QRect(10, 20, 581, 301))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tableResult.sizePolicy().hasHeightForWidth())
        self.tableResult.setSizePolicy(sizePolicy)
        self.tableResult.setMinimumSize(QtCore.QSize(0, 0))
        self.tableResult.setMaximumSize(QtCore.QSize(581, 16777215))
        self.tableResult.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.tableResult.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.tableResult.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.tableResult.setTabKeyNavigation(False)
        self.tableResult.setProperty("showDropIndicator", False)
        self.tableResult.setDragDropOverwriteMode(False)
        self.tableResult.setColumnCount(6)
        self.tableResult.setObjectName("tableResult")
        self.tableResult.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        item.setFont(font)
        self.tableResult.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableResult.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableResult.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableResult.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableResult.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.tableResult.setHorizontalHeaderItem(5, item)
        self.tableResult.horizontalHeader().setMinimumSectionSize(25)
        self.tableResult.verticalHeader().setVisible(False)
        self.tableResult.verticalHeader().setDefaultSectionSize(30)
        self.tableResult.verticalHeader().setHighlightSections(False)
        self.tableResult.verticalHeader().setMinimumSectionSize(17)
        self.groupBox_8 = QtWidgets.QGroupBox(self.tabMain)
        self.groupBox_8.setGeometry(QtCore.QRect(0, 510, 81, 41))
        self.groupBox_8.setObjectName("groupBox_8")
        self.testTimeLbl = QtWidgets.QLabel(self.groupBox_8)
        self.testTimeLbl.setGeometry(QtCore.QRect(10, 20, 61, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.testTimeLbl.setFont(font)
        self.testTimeLbl.setObjectName("testTimeLbl")
        self.layoutWidget = QtWidgets.QWidget(self.tabMain)
        self.layoutWidget.setGeometry(QtCore.QRect(210, 560, 201, 51))
        self.layoutWidget.setObjectName("layoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.layoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.currTestLbl = QtWidgets.QLabel(self.layoutWidget)
        self.currTestLbl.setObjectName("currTestLbl")
        self.verticalLayout.addWidget(self.currTestLbl)
        self.TestPrBar = QtWidgets.QProgressBar(self.layoutWidget)
        self.TestPrBar.setProperty("value", 24)
        self.TestPrBar.setObjectName("TestPrBar")
        self.verticalLayout.addWidget(self.TestPrBar)
        self.ConnectionBox = QtWidgets.QGroupBox(self.tabMain)
        self.ConnectionBox.setGeometry(QtCore.QRect(0, 550, 191, 61))
        self.ConnectionBox.setObjectName("ConnectionBox")
        self.layoutWidget_2 = QtWidgets.QWidget(self.ConnectionBox)
        self.layoutWidget_2.setGeometry(QtCore.QRect(10, 20, 171, 34))
        self.layoutWidget_2.setObjectName("layoutWidget_2")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.layoutWidget_2)
        self.gridLayout_2.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.labelPort = QtWidgets.QLabel(self.layoutWidget_2)
        self.labelPort.setObjectName("labelPort")
        self.gridLayout_2.addWidget(self.labelPort, 0, 0, 1, 1)
        self.labelBaud = QtWidgets.QLabel(self.layoutWidget_2)
        self.labelBaud.setObjectName("labelBaud")
        self.gridLayout_2.addWidget(self.labelBaud, 1, 0, 1, 1)
        self.movie = QtWidgets.QLabel(self.layoutWidget_2)
        self.movie.setText("")
        self.movie.setObjectName("movie")
        self.gridLayout_2.addWidget(self.movie, 0, 2, 2, 1)
        self.portLbl = QtWidgets.QLabel(self.layoutWidget_2)
        self.portLbl.setObjectName("portLbl")
        self.gridLayout_2.addWidget(self.portLbl, 0, 1, 1, 1)
        self.baudLbl = QtWidgets.QLabel(self.layoutWidget_2)
        self.baudLbl.setObjectName("baudLbl")
        self.gridLayout_2.addWidget(self.baudLbl, 1, 1, 1, 1)
        self.label3_2 = QtWidgets.QLabel(self.tabMain)
        self.label3_2.setGeometry(QtCore.QRect(422, 570, 55, 16))
        self.label3_2.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label3_2.setObjectName("label3_2")
        self.calibrLbl = QtWidgets.QLabel(self.tabMain)
        self.calibrLbl.setGeometry(QtCore.QRect(483, 570, 24, 16))
        self.calibrLbl.setObjectName("calibrLbl")
        self.label4 = QtWidgets.QLabel(self.tabMain)
        self.label4.setGeometry(QtCore.QRect(422, 591, 27, 16))
        self.label4.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label4.setObjectName("label4")
        self.dateCalibrLbl = QtWidgets.QLabel(self.tabMain)
        self.dateCalibrLbl.setGeometry(QtCore.QRect(455, 591, 51, 16))
        self.dateCalibrLbl.setObjectName("dateCalibrLbl")
        self.mainTabWidget.addTab(self.tabMain, "")
        self.tabJournal = QtWidgets.QWidget()
        self.tabJournal.setObjectName("tabJournal")
        self.tableJournal = QtWidgets.QTableWidget(self.tabJournal)
        self.tableJournal.setGeometry(QtCore.QRect(10, 40, 801, 511))
        self.tableJournal.viewport().setProperty("cursor", QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.tableJournal.setMouseTracking(True)
        self.tableJournal.setFocusPolicy(QtCore.Qt.WheelFocus)
        self.tableJournal.setToolTip("")
        self.tableJournal.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.tableJournal.setSelectionMode(QtWidgets.QAbstractItemView.SingleSelection)
        self.tableJournal.setObjectName("tableJournal")
        self.tableJournal.setColumnCount(15)
        self.tableJournal.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tableJournal.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableJournal.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableJournal.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableJournal.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableJournal.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableJournal.setHorizontalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableJournal.setHorizontalHeaderItem(6, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableJournal.setHorizontalHeaderItem(7, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableJournal.setHorizontalHeaderItem(8, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableJournal.setHorizontalHeaderItem(9, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableJournal.setHorizontalHeaderItem(10, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableJournal.setHorizontalHeaderItem(11, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableJournal.setHorizontalHeaderItem(12, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableJournal.setHorizontalHeaderItem(13, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableJournal.setHorizontalHeaderItem(14, item)
        self.tableJournal.horizontalHeader().setDefaultSectionSize(71)
        self.journalUpdateBtn = QtWidgets.QPushButton(self.tabJournal)
        self.journalUpdateBtn.setGeometry(QtCore.QRect(240, 10, 91, 21))
        self.journalUpdateBtn.setObjectName("journalUpdateBtn")
        self.journalDateStart = QtWidgets.QDateEdit(self.tabJournal)
        self.journalDateStart.setGeometry(QtCore.QRect(40, 10, 81, 22))
        self.journalDateStart.setLocale(QtCore.QLocale(QtCore.QLocale.Hebrew, QtCore.QLocale.Israel))
        self.journalDateStart.setObjectName("journalDateStart")
        self.journalDateStop = QtWidgets.QDateEdit(self.tabJournal)
        self.journalDateStop.setGeometry(QtCore.QRect(150, 11, 81, 21))
        self.journalDateStop.setLocale(QtCore.QLocale(QtCore.QLocale.Hebrew, QtCore.QLocale.Israel))
        self.journalDateStop.setObjectName("journalDateStop")
        self.printReportBtn = QtWidgets.QPushButton(self.tabJournal)
        self.printReportBtn.setGeometry(QtCore.QRect(230, 580, 91, 21))
        self.printReportBtn.setObjectName("printReportBtn")
        self.journalFilter = QtWidgets.QLineEdit(self.tabJournal)
        self.journalFilter.setGeometry(QtCore.QRect(370, 10, 91, 20))
        self.journalFilter.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.journalFilter.setText("")
        self.journalFilter.setMaxLength(16)
        self.journalFilter.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.journalFilter.setObjectName("journalFilter")
        self.label5 = QtWidgets.QLabel(self.tabJournal)
        self.label5.setGeometry(QtCore.QRect(340, 10, 31, 21))
        self.label5.setObjectName("label5")
        self.label6 = QtWidgets.QLabel(self.tabJournal)
        self.label6.setGeometry(QtCore.QRect(10, 10, 31, 21))
        self.label6.setObjectName("label6")
        self.label7 = QtWidgets.QLabel(self.tabJournal)
        self.label7.setGeometry(QtCore.QRect(130, 10, 16, 21))
        self.label7.setObjectName("label7")
        self.logoAxellRadio = QtWidgets.QRadioButton(self.tabJournal)
        self.logoAxellRadio.setGeometry(QtCore.QRect(10, 600, 51, 17))
        self.logoAxellRadio.setChecked(False)
        self.logoAxellRadio.setObjectName("logoAxellRadio")
        self.logoCobhamRadio = QtWidgets.QRadioButton(self.tabJournal)
        self.logoCobhamRadio.setGeometry(QtCore.QRect(10, 580, 61, 17))
        self.logoCobhamRadio.setChecked(True)
        self.logoCobhamRadio.setObjectName("logoCobhamRadio")
        self.reportTemplateCombo = QtWidgets.QComboBox(self.tabJournal)
        self.reportTemplateCombo.setGeometry(QtCore.QRect(80, 580, 131, 22))
        self.reportTemplateCombo.setObjectName("reportTemplateCombo")
        self.label8 = QtWidgets.QLabel(self.tabJournal)
        self.label8.setGeometry(QtCore.QRect(80, 560, 81, 16))
        self.label8.setObjectName("label8")
        self.label9 = QtWidgets.QLabel(self.tabJournal)
        self.label9.setGeometry(QtCore.QRect(10, 560, 81, 16))
        self.label9.setObjectName("label9")
        self.mainTabWidget.addTab(self.tabJournal, "")
        self.tabSettings = QtWidgets.QWidget()
        self.tabSettings.setObjectName("tabSettings")
        self.instrumentsGroupBox = QtWidgets.QGroupBox(self.tabSettings)
        self.instrumentsGroupBox.setGeometry(QtCore.QRect(10, 10, 541, 171))
        self.instrumentsGroupBox.setObjectName("instrumentsGroupBox")
        self.instrAddrCombo = QtWidgets.QComboBox(self.instrumentsGroupBox)
        self.instrAddrCombo.setGeometry(QtCore.QRect(10, 110, 191, 21))
        self.instrAddrCombo.setMouseTracking(True)
        self.instrAddrCombo.setObjectName("instrAddrCombo")
        self.setSaRadio = QtWidgets.QRadioButton(self.instrumentsGroupBox)
        self.setSaRadio.setGeometry(QtCore.QRect(10, 20, 41, 17))
        self.setSaRadio.setChecked(True)
        self.setSaRadio.setObjectName("setSaRadio")
        self.setGenRadio = QtWidgets.QRadioButton(self.instrumentsGroupBox)
        self.setGenRadio.setGeometry(QtCore.QRect(10, 50, 51, 17))
        self.setGenRadio.setObjectName("setGenRadio")
        self.label0 = QtWidgets.QLabel(self.instrumentsGroupBox)
        self.label0.setGeometry(QtCore.QRect(210, 110, 51, 20))
        self.label0.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label0.setObjectName("label0")
        self.label1 = QtWidgets.QLabel(self.instrumentsGroupBox)
        self.label1.setGeometry(QtCore.QRect(310, 110, 61, 20))
        self.label1.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label1.setObjectName("label1")
        self.saAtten = QtWidgets.QLineEdit(self.instrumentsGroupBox)
        self.saAtten.setGeometry(QtCore.QRect(270, 110, 31, 20))
        self.saAtten.setAlignment(QtCore.Qt.AlignCenter)
        self.saAtten.setObjectName("saAtten")
        self.genAtten = QtWidgets.QLineEdit(self.instrumentsGroupBox)
        self.genAtten.setGeometry(QtCore.QRect(380, 110, 31, 20))
        self.genAtten.setAlignment(QtCore.Qt.AlignCenter)
        self.genAtten.setObjectName("genAtten")
        self.setNaRadio = QtWidgets.QRadioButton(self.instrumentsGroupBox)
        self.setNaRadio.setGeometry(QtCore.QRect(10, 80, 51, 17))
        self.setNaRadio.setObjectName("setNaRadio")
        self.setInstrBtn = QtWidgets.QPushButton(self.instrumentsGroupBox)
        self.setInstrBtn.setGeometry(QtCore.QRect(110, 140, 91, 23))
        self.setInstrBtn.setObjectName("setInstrBtn")
        self.label21 = QtWidgets.QLabel(self.instrumentsGroupBox)
        self.label21.setGeometry(QtCore.QRect(420, 110, 71, 20))
        self.label21.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label21.setObjectName("label21")
        self.naAtten1 = QtWidgets.QLineEdit(self.instrumentsGroupBox)
        self.naAtten1.setGeometry(QtCore.QRect(500, 110, 31, 20))
        self.naAtten1.setAlignment(QtCore.Qt.AlignCenter)
        self.naAtten1.setObjectName("naAtten1")
        self.layoutWidget1 = QtWidgets.QWidget(self.instrumentsGroupBox)
        self.layoutWidget1.setGeometry(QtCore.QRect(80, 80, 451, 21))
        self.layoutWidget1.setObjectName("layoutWidget1")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.layoutWidget1)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.currNaLbl = QtWidgets.QLabel(self.layoutWidget1)
        self.currNaLbl.setObjectName("currNaLbl")
        self.horizontalLayout.addWidget(self.currNaLbl)
        self.currNaNameLbl = QtWidgets.QLabel(self.layoutWidget1)
        self.currNaNameLbl.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.currNaNameLbl.setObjectName("currNaNameLbl")
        self.horizontalLayout.addWidget(self.currNaNameLbl)
        self.layoutWidget2 = QtWidgets.QWidget(self.instrumentsGroupBox)
        self.layoutWidget2.setGeometry(QtCore.QRect(80, 50, 451, 21))
        self.layoutWidget2.setObjectName("layoutWidget2")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.layoutWidget2)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.currGenLbl = QtWidgets.QLabel(self.layoutWidget2)
        self.currGenLbl.setObjectName("currGenLbl")
        self.horizontalLayout_2.addWidget(self.currGenLbl)
        self.currGenNameLbl = QtWidgets.QLabel(self.layoutWidget2)
        self.currGenNameLbl.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.currGenNameLbl.setObjectName("currGenNameLbl")
        self.horizontalLayout_2.addWidget(self.currGenNameLbl)
        self.layoutWidget3 = QtWidgets.QWidget(self.instrumentsGroupBox)
        self.layoutWidget3.setGeometry(QtCore.QRect(80, 20, 451, 21))
        self.layoutWidget3.setObjectName("layoutWidget3")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.layoutWidget3)
        self.horizontalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.currSaLbl = QtWidgets.QLabel(self.layoutWidget3)
        self.currSaLbl.setObjectName("currSaLbl")
        self.horizontalLayout_3.addWidget(self.currSaLbl)
        self.currSaNameLbl = QtWidgets.QLabel(self.layoutWidget3)
        self.currSaNameLbl.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.currSaNameLbl.setObjectName("currSaNameLbl")
        self.horizontalLayout_3.addWidget(self.currSaNameLbl)
        self.line = QtWidgets.QFrame(self.instrumentsGroupBox)
        self.line.setGeometry(QtCore.QRect(60, 40, 471, 16))
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.line_2 = QtWidgets.QFrame(self.instrumentsGroupBox)
        self.line_2.setGeometry(QtCore.QRect(60, 70, 471, 16))
        self.line_2.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.updateInstrBtn = QtWidgets.QPushButton(self.instrumentsGroupBox)
        self.updateInstrBtn.setGeometry(QtCore.QRect(10, 140, 91, 23))
        self.updateInstrBtn.setObjectName("updateInstrBtn")
        self.saStat = QtWidgets.QLabel(self.instrumentsGroupBox)
        self.saStat.setGeometry(QtCore.QRect(60, 20, 16, 21))
        self.saStat.setObjectName("saStat")
        self.genStat = QtWidgets.QLabel(self.instrumentsGroupBox)
        self.genStat.setGeometry(QtCore.QRect(60, 50, 21, 21))
        self.genStat.setObjectName("genStat")
        self.naStat = QtWidgets.QLabel(self.instrumentsGroupBox)
        self.naStat.setGeometry(QtCore.QRect(60, 80, 21, 21))
        self.naStat.setObjectName("naStat")
        self.label2_2 = QtWidgets.QLabel(self.instrumentsGroupBox)
        self.label2_2.setGeometry(QtCore.QRect(420, 140, 71, 20))
        self.label2_2.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label2_2.setObjectName("label2_2")
        self.naAtten2 = QtWidgets.QLineEdit(self.instrumentsGroupBox)
        self.naAtten2.setGeometry(QtCore.QRect(500, 140, 31, 20))
        self.naAtten2.setAlignment(QtCore.Qt.AlignCenter)
        self.naAtten2.setObjectName("naAtten2")
        self.groupBox_10 = QtWidgets.QGroupBox(self.tabSettings)
        self.groupBox_10.setGeometry(QtCore.QRect(10, 180, 201, 151))
        self.groupBox_10.setObjectName("groupBox_10")
        self.layoutWidget4 = QtWidgets.QWidget(self.groupBox_10)
        self.layoutWidget4.setGeometry(QtCore.QRect(1, 20, 145, 22))
        self.layoutWidget4.setObjectName("layoutWidget4")
        self.gridLayout = QtWidgets.QGridLayout(self.layoutWidget4)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.label3 = QtWidgets.QLabel(self.layoutWidget4)
        self.label3.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label3.setObjectName("label3")
        self.gridLayout.addWidget(self.label3, 0, 0, 1, 1)
        self.testSetDsaFull = QtWidgets.QRadioButton(self.layoutWidget4)
        self.testSetDsaFull.setObjectName("testSetDsaFull")
        self.gridLayout.addWidget(self.testSetDsaFull, 0, 1, 1, 1)
        self.testSetDsaShort = QtWidgets.QRadioButton(self.layoutWidget4)
        self.testSetDsaShort.setChecked(True)
        self.testSetDsaShort.setObjectName("testSetDsaShort")
        self.gridLayout.addWidget(self.testSetDsaShort, 0, 2, 1, 1)
        self.calibrationGroupBox = QtWidgets.QGroupBox(self.tabSettings)
        self.calibrationGroupBox.setGeometry(QtCore.QRect(560, 60, 241, 121))
        self.calibrationGroupBox.setObjectName("calibrationGroupBox")
        self.calAllBands = QtWidgets.QCheckBox(self.calibrationGroupBox)
        self.calAllBands.setGeometry(QtCore.QRect(10, 20, 111, 17))
        self.calAllBands.setObjectName("calAllBands")
        self.layoutWidget5 = QtWidgets.QWidget(self.calibrationGroupBox)
        self.layoutWidget5.setGeometry(QtCore.QRect(10, 50, 222, 22))
        self.layoutWidget5.setObjectName("layoutWidget5")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.layoutWidget5)
        self.horizontalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.label41 = QtWidgets.QLabel(self.layoutWidget5)
        self.label41.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label41.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label41.setObjectName("label41")
        self.horizontalLayout_5.addWidget(self.label41)
        self.calibrStart = QtWidgets.QLineEdit(self.layoutWidget5)
        self.calibrStart.setMaxLength(4)
        self.calibrStart.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.calibrStart.setObjectName("calibrStart")
        self.horizontalLayout_5.addWidget(self.calibrStart)
        self.label61 = QtWidgets.QLabel(self.layoutWidget5)
        self.label61.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label61.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label61.setObjectName("label61")
        self.horizontalLayout_5.addWidget(self.label61)
        self.label51 = QtWidgets.QLabel(self.layoutWidget5)
        self.label51.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label51.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label51.setObjectName("label51")
        self.horizontalLayout_5.addWidget(self.label51)
        self.calibrStop = QtWidgets.QLineEdit(self.layoutWidget5)
        self.calibrStop.setMaxLength(4)
        self.calibrStop.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.calibrStop.setObjectName("calibrStop")
        self.horizontalLayout_5.addWidget(self.calibrStop)
        self.label71 = QtWidgets.QLabel(self.layoutWidget5)
        self.label71.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label71.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label71.setObjectName("label71")
        self.horizontalLayout_5.addWidget(self.label71)
        self.layoutWidget6 = QtWidgets.QWidget(self.calibrationGroupBox)
        self.layoutWidget6.setGeometry(QtCore.QRect(10, 80, 221, 25))
        self.layoutWidget6.setObjectName("layoutWidget6")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.layoutWidget6)
        self.horizontalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.calibrationBtn = QtWidgets.QPushButton(self.layoutWidget6)
        self.calibrationBtn.setObjectName("calibrationBtn")
        self.horizontalLayout_4.addWidget(self.calibrationBtn)
        self.clearCalBtn = QtWidgets.QPushButton(self.layoutWidget6)
        self.clearCalBtn.setObjectName("clearCalBtn")
        self.horizontalLayout_4.addWidget(self.clearCalBtn)
        self.rfbAtrGroupBox = QtWidgets.QGroupBox(self.tabSettings)
        self.rfbAtrGroupBox.setGeometry(QtCore.QRect(560, 10, 241, 51))
        self.rfbAtrGroupBox.setObjectName("rfbAtrGroupBox")
        self.newRfbBtn = QtWidgets.QPushButton(self.rfbAtrGroupBox)
        self.newRfbBtn.setGeometry(QtCore.QRect(150, 20, 81, 23))
        self.newRfbBtn.setObjectName("newRfbBtn")
        self.editRfbCombo = QtWidgets.QComboBox(self.rfbAtrGroupBox)
        self.editRfbCombo.setGeometry(QtCore.QRect(10, 20, 131, 22))
        self.editRfbCombo.setObjectName("editRfbCombo")
        self.applySetBtn = QtWidgets.QPushButton(self.tabSettings)
        self.applySetBtn.setEnabled(True)
        self.applySetBtn.setGeometry(QtCore.QRect(10, 340, 75, 23))
        self.applySetBtn.setObjectName("applySetBtn")
        self.mainTabWidget.addTab(self.tabSettings, "")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menuBar = QtWidgets.QMenuBar(MainWindow)
        self.menuBar.setGeometry(QtCore.QRect(0, 0, 840, 20))
        self.menuBar.setObjectName("menuBar")
        self.menuFile = QtWidgets.QMenu(self.menuBar)
        self.menuFile.setObjectName("menuFile")
        self.menuSettings = QtWidgets.QMenu(self.menuBar)
        self.menuSettings.setObjectName("menuSettings")
        MainWindow.setMenuBar(self.menuBar)
        self.menuExit = QtWidgets.QAction(MainWindow)
        self.menuExit.setObjectName("menuExit")
        self.menuSelectUser = QtWidgets.QAction(MainWindow)
        self.menuSelectUser.setObjectName("menuSelectUser")
        self.menuTestSettings = QtWidgets.QAction(MainWindow)
        self.menuTestSettings.setObjectName("menuTestSettings")
        self.menuFile.addAction(self.menuSelectUser)
        self.menuFile.addAction(self.menuExit)
        self.menuSettings.addAction(self.menuTestSettings)
        self.menuBar.addAction(self.menuFile.menuAction())
        self.menuBar.addAction(self.menuSettings.menuAction())

        self.retranslateUi(MainWindow)
        self.mainTabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
        MainWindow.setTabOrder(self.listLog, self.clrLogBtn)
        MainWindow.setTabOrder(self.clrLogBtn, self.startTestBtn)
        MainWindow.setTabOrder(self.startTestBtn, self.checkAlcTest)
        MainWindow.setTabOrder(self.checkAlcTest, self.rfbTypeCombo)
        MainWindow.setTabOrder(self.rfbTypeCombo, self.checkGainTest)
        MainWindow.setTabOrder(self.checkGainTest, self.mainTabWidget)
        MainWindow.setTabOrder(self.mainTabWidget, self.checkDsaTest)
        MainWindow.setTabOrder(self.checkDsaTest, self.checkBitAlarmTest)
        MainWindow.setTabOrder(self.checkBitAlarmTest, self.checkImTest)
        MainWindow.setTabOrder(self.checkImTest, self.rfbSN)
        MainWindow.setTabOrder(self.rfbSN, self.tableSettings)
        MainWindow.setTabOrder(self.tableSettings, self.tableResult)
        MainWindow.setTabOrder(self.tableResult, self.tableJournal)
        MainWindow.setTabOrder(self.tableJournal, self.journalUpdateBtn)
        MainWindow.setTabOrder(self.journalUpdateBtn, self.journalDateStart)
        MainWindow.setTabOrder(self.journalDateStart, self.journalDateStop)
        MainWindow.setTabOrder(self.journalDateStop, self.printReportBtn)
        MainWindow.setTabOrder(self.printReportBtn, self.journalFilter)
        MainWindow.setTabOrder(self.journalFilter, self.logoAxellRadio)
        MainWindow.setTabOrder(self.logoAxellRadio, self.logoCobhamRadio)
        MainWindow.setTabOrder(self.logoCobhamRadio, self.reportTemplateCombo)
        MainWindow.setTabOrder(self.reportTemplateCombo, self.instrAddrCombo)
        MainWindow.setTabOrder(self.instrAddrCombo, self.setSaRadio)
        MainWindow.setTabOrder(self.setSaRadio, self.setGenRadio)
        MainWindow.setTabOrder(self.setGenRadio, self.saAtten)
        MainWindow.setTabOrder(self.saAtten, self.genAtten)
        MainWindow.setTabOrder(self.genAtten, self.saAtten)
        MainWindow.setTabOrder(self.saAtten, self.setNaRadio)
        MainWindow.setTabOrder(self.setNaRadio, self.setInstrBtn)
        MainWindow.setTabOrder(self.setInstrBtn, self.naAtten1)
        MainWindow.setTabOrder(self.naAtten1, self.testSetDsaFull)
        MainWindow.setTabOrder(self.testSetDsaFull, self.testSetDsaShort)
        MainWindow.setTabOrder(self.testSetDsaShort, self.calibrationBtn)
        MainWindow.setTabOrder(self.calibrationBtn, self.clearCalBtn)
        MainWindow.setTabOrder(self.clearCalBtn, self.calAllBands)
        MainWindow.setTabOrder(self.calAllBands, self.calibrStart)
        MainWindow.setTabOrder(self.calibrStart, self.calibrStop)
        MainWindow.setTabOrder(self.calibrStop, self.newRfbBtn)
        MainWindow.setTabOrder(self.newRfbBtn, self.editRfbCombo)
        MainWindow.setTabOrder(self.editRfbCombo, self.applySetBtn)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        self.logGroupBox.setTitle(_translate("MainWindow", "Log"))
        self.clrLogBtn.setText(_translate("MainWindow", "Clear Log"))
        self.label_9.setText(_translate("MainWindow", "RFB type:"))
        self.startTestBtn.setText(_translate("MainWindow", "Start"))
        self.testsGroupBox.setTitle(_translate("MainWindow", "Tests"))
        self.checkAlcTest.setText(_translate("MainWindow", "ALC"))
        self.checkGainTest.setText(_translate("MainWindow", "Gain and flatness"))
        self.checkDsaTest.setText(_translate("MainWindow", "DSA"))
        self.checkBitAlarmTest.setText(_translate("MainWindow", "BIT alarm"))
        self.checkImTest.setText(_translate("MainWindow", "Intermodulation"))
        self.label2.setText(_translate("MainWindow", "RFB SN:"))
        item = self.tableSettings.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Settings"))
        item = self.tableSettings.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Value"))
        self.groupBox_7.setTitle(_translate("MainWindow", "Result"))
        item = self.tableResult.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Test name"))
        item = self.tableResult.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Dl/Ul"))
        item = self.tableResult.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "Min"))
        item = self.tableResult.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "Current"))
        item = self.tableResult.horizontalHeaderItem(4)
        item.setText(_translate("MainWindow", "Max"))
        item = self.tableResult.horizontalHeaderItem(5)
        item.setText(_translate("MainWindow", "Result"))
        self.groupBox_8.setTitle(_translate("MainWindow", "Test timer"))
        self.testTimeLbl.setText(_translate("MainWindow", "0:00:00"))
        self.currTestLbl.setText(_translate("MainWindow", "none"))
        self.ConnectionBox.setTitle(_translate("MainWindow", "Connection"))
        self.labelPort.setText(_translate("MainWindow", "Port :"))
        self.labelBaud.setText(_translate("MainWindow", "Baud:"))
        self.portLbl.setText(_translate("MainWindow", "port"))
        self.baudLbl.setText(_translate("MainWindow", "baud"))
        self.label3_2.setText(_translate("MainWindow", "Calibration:"))
        self.calibrLbl.setText(_translate("MainWindow", "none"))
        self.label4.setText(_translate("MainWindow", "Date:"))
        self.dateCalibrLbl.setText(_translate("MainWindow", "none"))
        self.mainTabWidget.setTabText(self.mainTabWidget.indexOf(self.tabMain), _translate("MainWindow", "Main"))
        self.tableJournal.setSortingEnabled(False)
        item = self.tableJournal.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "RFB type"))
        item = self.tableJournal.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "DSA 1"))
        item = self.tableJournal.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "Date test"))
        item = self.tableJournal.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "Band"))
        item = self.tableJournal.horizontalHeaderItem(4)
        item.setText(_translate("MainWindow", "Gain"))
        item = self.tableJournal.horizontalHeaderItem(5)
        item.setText(_translate("MainWindow", "Flatness"))
        item = self.tableJournal.horizontalHeaderItem(6)
        item.setText(_translate("MainWindow", "New Column"))
        item = self.tableJournal.horizontalHeaderItem(7)
        item.setText(_translate("MainWindow", "DSA 2"))
        item = self.tableJournal.horizontalHeaderItem(8)
        item.setText(_translate("MainWindow", "DSA 3"))
        item = self.tableJournal.horizontalHeaderItem(9)
        item.setText(_translate("MainWindow", "IMod"))
        item = self.tableJournal.horizontalHeaderItem(10)
        item.setText(_translate("MainWindow", "BIT"))
        item = self.tableJournal.horizontalHeaderItem(11)
        item.setText(_translate("MainWindow", "ALC In"))
        item = self.tableJournal.horizontalHeaderItem(12)
        item.setText(_translate("MainWindow", "ALC Out"))
        item = self.tableJournal.horizontalHeaderItem(13)
        item.setText(_translate("MainWindow", "Status"))
        item = self.tableJournal.horizontalHeaderItem(14)
        item.setText(_translate("MainWindow", "User"))
        self.journalUpdateBtn.setText(_translate("MainWindow", "Update"))
        self.journalDateStart.setDisplayFormat(_translate("MainWindow", "dd.MM.yyyy"))
        self.journalDateStop.setDisplayFormat(_translate("MainWindow", "dd.MM.yyyy"))
        self.printReportBtn.setText(_translate("MainWindow", "Print report"))
        self.label5.setText(_translate("MainWindow", "Filter:"))
        self.label6.setText(_translate("MainWindow", "From:"))
        self.label7.setText(_translate("MainWindow", "To:"))
        self.logoAxellRadio.setText(_translate("MainWindow", "Axell"))
        self.logoCobhamRadio.setText(_translate("MainWindow", "Cobham"))
        self.label8.setText(_translate("MainWindow", "Report template:"))
        self.label9.setText(_translate("MainWindow", "Logo:"))
        self.mainTabWidget.setTabText(self.mainTabWidget.indexOf(self.tabJournal), _translate("MainWindow", "Journal"))
        self.instrumentsGroupBox.setTitle(_translate("MainWindow", "Instruments"))
        self.setSaRadio.setText(_translate("MainWindow", "SA:"))
        self.setGenRadio.setText(_translate("MainWindow", "GEN:"))
        self.label0.setText(_translate("MainWindow", "SA atten.:"))
        self.label1.setText(_translate("MainWindow", "GEN atten.:"))
        self.setNaRadio.setText(_translate("MainWindow", "NA:"))
        self.setInstrBtn.setText(_translate("MainWindow", "Set"))
        self.label21.setText(_translate("MainWindow", "NA atten. P1:"))
        self.currNaLbl.setText(_translate("MainWindow", "TextLabel"))
        self.currNaNameLbl.setText(_translate("MainWindow", "TextLabel"))
        self.currGenLbl.setText(_translate("MainWindow", "TextLabel"))
        self.currGenNameLbl.setText(_translate("MainWindow", "TextLabel"))
        self.currSaLbl.setText(_translate("MainWindow", "TextLabel"))
        self.currSaNameLbl.setText(_translate("MainWindow", "TextLabel"))
        self.updateInstrBtn.setText(_translate("MainWindow", "Update"))
        self.saStat.setText(_translate("MainWindow", "saStat"))
        self.genStat.setText(_translate("MainWindow", "genStat"))
        self.naStat.setText(_translate("MainWindow", "naStat"))
        self.label2_2.setText(_translate("MainWindow", "NA atten. P2:"))
        self.groupBox_10.setTitle(_translate("MainWindow", "Test settings"))
        self.label3.setText(_translate("MainWindow", "DSA:"))
        self.testSetDsaFull.setText(_translate("MainWindow", "full"))
        self.testSetDsaShort.setText(_translate("MainWindow", "short"))
        self.calibrationGroupBox.setTitle(_translate("MainWindow", "Calibration"))
        self.calAllBands.setText(_translate("MainWindow", "Calibtate all bands"))
        self.label41.setText(_translate("MainWindow", "Start:"))
        self.label61.setText(_translate("MainWindow", "MHz"))
        self.label51.setText(_translate("MainWindow", "Stop:"))
        self.label71.setText(_translate("MainWindow", "MHz"))
        self.calibrationBtn.setText(_translate("MainWindow", "Calibration"))
        self.clearCalBtn.setText(_translate("MainWindow", "Clear cal.table"))
        self.rfbAtrGroupBox.setTitle(_translate("MainWindow", "RFB ATR settings"))
        self.newRfbBtn.setText(_translate("MainWindow", "New/Edit"))
        self.applySetBtn.setText(_translate("MainWindow", "Apply SetFile"))
        self.mainTabWidget.setTabText(self.mainTabWidget.indexOf(self.tabSettings), _translate("MainWindow", "Settings"))
        self.menuFile.setTitle(_translate("MainWindow", "File"))
        self.menuSettings.setTitle(_translate("MainWindow", "Settings"))
        self.menuExit.setText(_translate("MainWindow", "Exit"))
        self.menuSelectUser.setText(_translate("MainWindow", "Select user"))
        self.menuTestSettings.setText(_translate("MainWindow", "Test settings"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())

