# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'RFBedit.ui'
#
# Created: Wed Feb 21 11:12:28 2018
#      by: PyQt5 UI code generator 5.2.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_RFBedit(object):
    def setupUi(self, RFBedit):
        RFBedit.setObjectName("RFBedit")
        RFBedit.setWindowModality(QtCore.Qt.ApplicationModal)
        RFBedit.resize(521, 385)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("../Img/ico32_pgn_icon.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        RFBedit.setWindowIcon(icon)
        self.tableAtrSettings = QtWidgets.QTableWidget(RFBedit)
        self.tableAtrSettings.setGeometry(QtCore.QRect(10, 80, 241, 261))
        self.tableAtrSettings.setObjectName("tableAtrSettings")
        self.tableAtrSettings.setColumnCount(2)
        self.tableAtrSettings.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        item.setFont(font)
        self.tableAtrSettings.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        item.setFont(font)
        self.tableAtrSettings.setHorizontalHeaderItem(1, item)
        self.closeBtn = QtWidgets.QPushButton(RFBedit)
        self.closeBtn.setGeometry(QtCore.QRect(430, 350, 75, 23))
        self.closeBtn.setObjectName("closeBtn")
        self.saveBtn = QtWidgets.QPushButton(RFBedit)
        self.saveBtn.setGeometry(QtCore.QRect(10, 350, 75, 23))
        self.saveBtn.setObjectName("saveBtn")
        self.tableTestSettings = QtWidgets.QTableWidget(RFBedit)
        self.tableTestSettings.setGeometry(QtCore.QRect(260, 80, 241, 261))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tableTestSettings.sizePolicy().hasHeightForWidth())
        self.tableTestSettings.setSizePolicy(sizePolicy)
        self.tableTestSettings.setObjectName("tableTestSettings")
        self.tableTestSettings.setColumnCount(2)
        self.tableTestSettings.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        item.setFont(font)
        self.tableTestSettings.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        item.setFont(font)
        self.tableTestSettings.setHorizontalHeaderItem(1, item)
        self.widget = QtWidgets.QWidget(RFBedit)
        self.widget.setGeometry(QtCore.QRect(40, 10, 411, 53))
        self.widget.setObjectName("widget")
        self.gridLayout = QtWidgets.QGridLayout(self.widget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label = QtWidgets.QLabel(self.widget)
        self.label.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        self.rfbName = QtWidgets.QLineEdit(self.widget)
        self.rfbName.setObjectName("rfbName")
        self.horizontalLayout.addWidget(self.rfbName)
        self.gridLayout.addLayout(self.horizontalLayout, 0, 0, 1, 1)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_2 = QtWidgets.QLabel(self.widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_2.sizePolicy().hasHeightForWidth())
        self.label_2.setSizePolicy(sizePolicy)
        self.label_2.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_2.addWidget(self.label_2)
        self.ademCombo = QtWidgets.QComboBox(self.widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ademCombo.sizePolicy().hasHeightForWidth())
        self.ademCombo.setSizePolicy(sizePolicy)
        self.ademCombo.setMaximumSize(QtCore.QSize(133, 16777215))
        self.ademCombo.setObjectName("ademCombo")
        self.horizontalLayout_2.addWidget(self.ademCombo)
        self.gridLayout.addLayout(self.horizontalLayout_2, 0, 1, 1, 1)
        self.showAllBtn = QtWidgets.QPushButton(self.widget)
        self.showAllBtn.setObjectName("showAllBtn")
        self.gridLayout.addWidget(self.showAllBtn, 1, 0, 1, 1)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_3 = QtWidgets.QLabel(self.widget)
        self.label_3.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_3.addWidget(self.label_3)
        self.newAdem = QtWidgets.QLineEdit(self.widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.newAdem.sizePolicy().hasHeightForWidth())
        self.newAdem.setSizePolicy(sizePolicy)
        self.newAdem.setObjectName("newAdem")
        self.horizontalLayout_3.addWidget(self.newAdem)
        self.gridLayout.addLayout(self.horizontalLayout_3, 1, 1, 1, 1)

        self.retranslateUi(RFBedit)
        QtCore.QMetaObject.connectSlotsByName(RFBedit)

    def retranslateUi(self, RFBedit):
        _translate = QtCore.QCoreApplication.translate
        RFBedit.setWindowTitle(_translate("RFBedit", "RFB settings edit..."))
        item = self.tableAtrSettings.horizontalHeaderItem(0)
        item.setText(_translate("RFBedit", "Paremetr"))
        item = self.tableAtrSettings.horizontalHeaderItem(1)
        item.setText(_translate("RFBedit", "Value"))
        self.closeBtn.setText(_translate("RFBedit", "Close"))
        self.saveBtn.setText(_translate("RFBedit", "Save"))
        item = self.tableTestSettings.horizontalHeaderItem(0)
        item.setText(_translate("RFBedit", "Paremetr"))
        item = self.tableTestSettings.horizontalHeaderItem(1)
        item.setText(_translate("RFBedit", "Value"))
        self.label.setText(_translate("RFBedit", "RFB:"))
        self.label_2.setText(_translate("RFBedit", "        Adem:"))
        self.showAllBtn.setText(_translate("RFBedit", "Show all"))
        self.label_3.setText(_translate("RFBedit", "New adem:"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    RFBedit = QtWidgets.QDialog()
    ui = Ui_RFBedit()
    ui.setupUi(RFBedit)
    RFBedit.show()
    sys.exit(app.exec_())

